- build/package.sh
- cmd/manager/main.go
- docs/Ingress.md
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/resources/util.go
Fixed bug where random secret generation sometimes contained braces that broke ansible's YAML parser, causing pods to fail to start up
Fixed bad image name in build/package.sh, and added check for errors
Added s2s port to indexers
Added HEC endpoint to ingress doc examples
> Bug fixes and updated ingress examples for HEC

- Makefile
- README.md
- deploy/all-in-one-cluster.yaml
- deploy/all-in-one-scoped.yaml
- deploy/cluster_operator.yaml
- deploy/crds/enterprise_v1alpha1_splunkenterprise_crd.yaml
- deploy/operator.yaml
- deploy/rbac.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
- docs/ChangeLog.md
- docs/Examples.md
- docs/Ingress.md
- docs/Install.md
- docs/README.md
- pkg/controller/splunkenterprise/splunkenterprise_controller.go
- pkg/splunk/deploy/deployment.go
- pkg/splunk/deploy/launch.go
- pkg/splunk/deploy/statefulset.go
- pkg/splunk/deploy/util.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/names.go
- pkg/splunk/resources/util.go
- pkg/splunk/spark/configuration.go
- version/version.go
Fixed deadlock condition between deployer and search heads when apps_location is specified (note this this also requires a patch in splunk-ansible splunk/splunk-ansible#312
Updated auto-generated secrets to use alpha-numeric characters only to prevent escaping errors. This was after running into yet more circumstances where ansible plays would fail due to random bytes selected.
Updated auto-generated hec_token secret to use UUID like format
Updates to ensure HEC is always enabled by default
Updates to Ingress examples to include S2S and consolidate HEC
Added examples for app installation and custom config
> Various fixes

- pkg/splunk/enterprise/configuration.go
Fixes #10 when combined with a splunk/splunk image that includes this splunk-ansible fix:
https://github.com/splunk/splunk-ansible/pull/356
Should work ok for splunk-operator > 0.0.6 and splunk/splunk > 8.0.1
> Added splunk.pass4SymmKey to default secrets

- docs/SplunkEnterprise.md
- pkg/splunk/deploy/launch.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
Previously, the operator only allowed creation of clusters if a licenseURL was provided.
A license is not actually required to create clusters. Without providing a license, a time-limited trial will be created. This is especially desirable for testing.
This changes the behavior so that clusters may be created without a license. When a licenseURL is not provided, the license master will not be created and the pods in the deployment will not be configured to use a license master.
> Do not require licenseURL for clusters

- Makefile
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_sparks_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/0.1.0/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/0.1.0/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/0.1.0/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/0.1.0/enterprise.splunk.com_sparks_crd.yaml
- deploy/olm-catalog/splunk/0.1.0/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1alpha2/common_types.go
- pkg/apis/enterprise/v1alpha2/zz_generated.deepcopy.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/reconcile/util.go
- pkg/splunk/resources/util.go
- pkg/splunk/resources/util_test.go
- pkg/splunk/spark/configuration.go
#67 
- Add tolerations field to CommonSpec to pass thru to StatefulSet and Deployment (Spark)
- Refactored CompareXXX() routines to use sortAndCompareSlices()
> Support taint toleration

- .circleci/config.yml
- .gitignore
- Makefile
- go.mod
- go.sum
- test/README.md
- test/deploy-cluster.sh
- test/deploy-eks-cluster.sh
- test/deploy-kind-cluster.sh
- test/env.sh
- test/example/example1_test.go
- test/example/example2_test.go
- test/example/example_suite_test.go
- test/run-tests.sh
- test/smoke/smoke_suite_test.go
- test/smoke/smoke_test.go
- test/testenv/deployment.go
- test/testenv/testenv.go
- test/testenv/util.go
This PR
- adds the test framework using Ginkgo. It is under /test/testenv (Please see /test/README doc for more details).
- adds 2 basic tests using the test framework. The tests deploy a standalone (s2) and clustered (c3 - 3 indexers, 3 shs) and verified they are deployed and "ready".
- adds test scripts under /test to deploy kind or eks cluster and run the tests (Please see README doc under /test for details).
- updates Makefile and circleci's config.yaml to deploy the cluster and run the tests in the pipeline.
> Integration test framework and basic tests

- build/make_bundle.sh
Fixing the 'make generate' failure on Mac OS, i.e due to the way sed expects -i option.
> Cspl 409 make generate fails on mac os

- pkg/splunk/controller/messages.go
- pkg/splunk/controller/secret.go
- pkg/splunk/controller/secret_test.go
Fixing https://jira.splunk.com/browse/CSPL-300. Fixed update scenario + Unit testing.
Added a copyright message also in a couple of newly created files.
> Fix CSPL_300 - update secret scenario and added unit testing

- test/smoke/smoke_test.go
- test/testenv/deployment.go
Fixed formatting errors causing `make fmt` to fail.
> Fixed formatting to resolve make fmt failure

- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1alpha3/common_types.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/names.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- pkg/splunk/test/controller.go
- When the CR is configured for  Smartstore indexes in yaml format, convert that config
into INI stanza format, and write a configMap, which can be later mounted to the indexer
as indexes.conf.
> cspl-348: K8 SmartStore: Create a Config map for the indexes configuration in INI format

- pkg/splunk/enterprise/secrets.go
The data in the namespace scoped secret on deletion of all tokens reverts to a nil map. In such a case making sure that we are creating an empty map to avoid a nil pointer reference(hence crash on operator).
Fixing https://jira.splunk.com/browse/CSPL-450
> Fix CSPL_450 to address empty secret data map

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_sparks_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1alpha3/common_types.go
- pkg/splunk/client/enterprise.go
- pkg/splunk/client/enterprise_test.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/finalizers_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
Automate Splunk monitoring console app for indexer clustering
- Add cluster master URL to MC configMap
- Add MC as a searchhead on CM to get indexer info
- Automate the "Apply Changes" button on the monitoring console app when IndexerCluster custom resource is applied
- For multi-site get cluster-info and append "SPLUNK_SITE" and "SPLUNK_MULTISITE_MASTER" env variables to MC
> Automate splunk monitoring console app for indexer clustering

- pkg/splunk/controller/util.go
Update the Pod Spec, when there is a change in InitContainer list.
> cspl-490: Configuring Smartstore post deployment doesn't create splunk operator app

- build/make_bundle.sh
- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_sparks_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/examples/clustermaster/default.yaml
- deploy/examples/licensemaster/default.yaml
- deploy/examples/searchheadcluster/default.yaml
- deploy/examples/spark/default.yaml
- deploy/examples/standalone/default.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_sparks_crd.yaml
- deploy/olm-catalog/splunk/0.2.0/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/splunk.package.yaml
- docs/CustomResources.md
- docs/FAQ.md
- docs/README.md
In the CRD version change from v1alpha3 to v1beta1 via this PR, the examples under the deploy directory and CustomResources.md were left unchanged. Changing them as a correction via this PR.
> Fix CRD version in examples under deploy directory and CustomResources.md

- docs/Examples.md
- docs/README.md
> Documentation for monitoring console

- docs/Examples.md
- docs/SmartStore.md
> cspl-523: Update SmartStore.md

- pkg/splunk/enterprise/finalizers.go
- pkg/splunk/enterprise/finalizers_test.go
**Problem**
When we were trying to delete ClusterMaster first, then it was also deleting PVCs for IndexerCluster too( in addition to its own PVC).
This was happening because we were looking for PVCs which match the label **app.kubernetes.io/part-of** and all the PVCs of IndexerCluster and PVC of ClusterMaster had this same label. Hence it was deleting all the PVCs.
**Solution**
Now, instead of looking for PVCs with label **app.kubernetes.io/part-of**, we are looking for PVCs with label **app.kubernetes.io/instance**, which is unique per CR and hence only those PVCs which are associated with that PR will be deleted.
> CSPL-529: Fixing a bug where if we delete CM, it also deletes PVCs for IndexerCluster too

- test/smoke/smoke_test.go
- test/testenv/mcutil.go
- test/testenv/testenv.go
Made following changes to address flakiness related to MC test. 
* Changed wait time to 1500 seconds. 
* Added check to verify MC pod stays in ready state.
> CSPL-521: Added more delay and checks for MC pod to be ready

- docs/README.md
Update readme.md for platforms tested by operator
> CSPL-562 - Update readme.md for platforms tested by operator

- test/ingest_search/ingest_search_suite_test.go
- test/ingest_search/ingest_search_test.go
- test/testenv/ingest_utils.go
- test/testenv/search_utils.go
- Add test utils for running searches against Splunk instances
- Add test utils for creating and ingesting log files
- Add test suite that ingests a log and searches it
Verify that new smoke tests pass.
> CSPL-441 Create utilities to search and ingest data on a pod

- docs/Examples.md
- pkg/splunk/client/enterprise.go
- pkg/splunk/enterprise/finalizers_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/util/secrets_test.go
**Problem**
In case if IndexerCluster spec has replicas < replication_factor or site_replication_factor as set on ClusterMaster, then IndexerCluster goes in the reconcilation loop since CM is never in Ready state. And the only way to scale indexer cluster is using kubectl scale statefulset .....
**Solution**
Set replicas = RF if it is less than RF.
> bugfix/CSPL-466: If in IndexerCluster spec, replicas < RF(which is configured on ClusterMaster), then set replicas=RF.

- pkg/splunk/client/enterprise.go
- pkg/splunk/client/enterprise_test.go
- pkg/splunk/controller/configmap_test.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/util_test.go
UT Code coverage for Smartstore/Indexmanagement area of code
> cspl-558: Improve code coverage for Index management

- test/deploy-eks-cluster.sh
- test/env.sh
Updated the eks cluster create script to use existing VPC to avoid resource bottleneck on AWS.
- Added 2 environment variable in env.sh for existing public and private subnet string.
- Updated eksctl create command to use existing subnets.
> Eks use existing vpc

- docs/CustomResources.md
Seeing an error when applying example yaml in [doc](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#indexercluster-resource-spec-parameters):
```
apiVersion: enterprise.splunk.com/v1beta1
kind: IndexerCluster
metadata:
name: example
spec:
replicas: 3
clusterMasterRef: example-cm
```
```
The IndexerCluster "example" is invalid: spec.clusterMasterRef: Invalid value: "string": spec.clusterMasterRef in body must be of type object: "string"
```
turns out the ref should be a map instead of pure string
operator: `docker.io/splunk/splunk-operator:0.2.0`
configs:
- master:
```
apiVersion: enterprise.splunk.com/v1beta1
kind: ClusterMaster
metadata:
name: example-cm
```
- indexer cluster (this works)
```
apiVersion: enterprise.splunk.com/v1beta1
kind: IndexerCluster …
```
> fix IndexerCluster clusterMasterRef yaml in doc

- docs/Examples.md
- docs/PasswordManagement.md
Renamed a few occurrences of the keyword pass4symmkey to **pass4Symmkey**
> Docs fix for pass4Symmkey

- pkg/apis/enterprise/v1beta1/indexercluster_types.go
- pkg/apis/enterprise/v1beta1/searchheadcluster_types.go
- pkg/splunk/controller/statefulset.go
- pkg/splunk/controller/statefulset_test.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/test/controller.go
This PR fixes the problem of unnecessary pod resets/recycles during scale up/down of splunk resources. As part of this solution, as soon as we try to scale up/down pods, we now update the `pod-revision-hash` label on pods to match `updateRevision` of StatefulSet. This prevents the recycle of pods based on `pod-revision-hash` mismatch of pods.
> CSPL-534: Fix unnecessary pod recycle during scale up/down

- pkg/splunk/controller/util.go
- pkg/splunk/controller/util_test.go
When applying an updated CRD, check the environment variables and push those changes to the running pods.  For example, if the `defaultsUrl` parameter is changed in the CRD yaml and applied; the change is accepted however it is not reflected in the stateful set or the pod itself:
```
$ kubectl apply -f standalone6.yml 
standalone.enterprise.splunk.com/s6 created
$ kubectl describe pod/splunk-s6-standalone-0 
Name:         splunk-s6-standalone-0
Namespace:    default
...
Containers:
splunk:
Container ID:   containerd://0982abc2b231545a364eb1da6f4ac3d04358002b75942cb0c01609c7ac5bbe08
Image:          docker.io/splunk/splunk:8.1.0
...
Environment:
SPLUNK_HOME:                        /opt/splunk
SPLUNK_START_ARGS:                  --accept-license
SPLUNK_DEFAULTS_URL: …
```
> CSPL-592 Trigger app install on defaultsURL change

- docs/Examples.md
Fix in documentation for defaults configuration of passwords. Addresses the following [github issue](https://github.com/splunk/splunk-operator/issues/204).
> Docs fix for using defaults

- docs/MultisiteExamples.md
The example yamls for Splunk Enterprise deployments in Multisite examples documentation was missing the API version. Added the **v1beta1** api version for the Splunk Enterprise CRDs.
> Adding API version in multisite examples docs

- test/smoke/smoke_test.go
- test/testenv/deployment.go
- test/testenv/testenv.go
- test/testenv/util.go
- test/testenv/verificationutils.go
* Smoke test to verify service account attaches to standalone.
* Added new role needed for service account
* Added util to get service role name from pod
* Added verification util to compare serviceAccount on Pod to expected serviceAccount
> Smoke test to verify service account attaches to standalone.

- .circleci/config.yml
- test/env.sh
- test/run-tests.sh
- test/smartstore/smartstore_suite_test.go
- test/smartstore/smartstore_test.go
- test/testenv/cmutil.go
- test/testenv/deployment.go
- test/testenv/ingest_utils.go
- test/testenv/lmutil.go
- test/testenv/remote_index_utils.go
- test/testenv/s3utils.go
- test/testenv/testenv.go
- test/testenv/util.go
- test/testenv/verificationutils.go
* Added utilities need for S3 Index test cases
* Created a new test suite for Index Management
* Created S3 utilities to get object from S3 and verify object exists on S3
> CSPL-540: Added utilities and test for s3 indexes

- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_sparks_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/0.2.2/splunk.v0.2.2.clusterserviceversion.yaml
- deploy/operator.yaml
- docs/ChangeLog.md
- docs/Install.md
- docs/README.md
- version/version.go
Helper commit for 0.2.2 release
> Helper commit for 0.2.2 release

- .circleci/config.yml
- test/licensemaster/lm_suite_test.go
- test/licensemaster/lm_test.go
- test/smoke/smoke_test.go
- test/testenv/testenv.go
This PR adds a License Master test folder with several tests which verify indexers and SHs are well configured with  LM.
LM tests are added for following deployments:
- Standalone deployment (S1) with LM
- Clustered deployment (C3 - clustered indexer) with LM
- Clustered deployment (C3 - clustered indexer, search head cluster)
- Multisite cluster deployment (M13 - Multisite indexer cluster, Search head cluster)
- Multisite cluster deployment (M1 - multisite indexer cluster)
This PR also removes all tests with LM from smoke, so it can be run on customers environment without need of S3 access.
> CSPL-827: Improve automation to include License Master on several deployments

- test/run-tests.sh
- test/testenv/deployment.go
- test/testenv/testenv.go
Utility function to update spec.
Tested locally to update secret object:
1] {"level":"info","ts":1614280851.021538,"msg":"Checking status of Monitoring Console Pod"}
[1] {"level":"info","ts":1614280851.2303622,"msg":"MC statefulset found","POD":"splunk-smoke-sr-monitoring-console","READY":"1/1"}
[1] {"level":"info","ts":1614280851.447619,"msg":"MC Pod Found","POD":"splunk-smoke-sr-monitoring-console-0","READY":"1/1"}
[1] {"level":"info","ts":1614280851.677591,"msg":"NAME                                   READY   STATUS    RESTARTS   AGE"}
[1] {"level":"info","ts":1614280851.677645,"msg":"splunk-op-smoke-sr-5fd878654d-nkbbg    1/1     Running   0          5m35s"}
[1] {"level":"info","ts":1614280851.67765,"msg":"splunk-smoke-sr-monitoring-console-0   1/1     Running   0          95s"}
[1] …
> CSPL-879: Utility to apply updated spec

- go.mod
- go.sum
Upgrade golang text library to v0.3.5 to fix CVE-2020-14040 and CVE-2020-28852
> CSPL-835 Upgrade golang text library to v0.3.5

- go.mod
- go.sum
A Whitesource scan of the operator branch revealed it is vulnerable to CVE-2020-8911 and CVE-2020-8912
CVE-2020-8911 is fixed by upgrading the aws-sdk-go library to v1.34.1 or later.
CVE-2020-8912 is fixed by upgrading the aws-sdk-go library to v1.28.3 or later.
> CSPL-841 Upgrade aws-sdk-go version to v1.34.1 or later

- .circleci/config.yml
- test/licensemaster/lm_test.go
- test/scaling_test/scaling_test.go
- test/secret/secret_suite_test.go
- test/secret/secret_test.go
- test/smartstore/smartstore_test.go
- test/testenv/secretutil.go
- test/testenv/testenv.go
- test/testenv/verificationutils.go
Automation for secret object update on splunk.
Test scenarios:
1. Standalone Pod
2. Clustered deployment (C3 - clustered indexer, search head cluster)
3. Multisite cluster deployment (M13 - Multisite indexer cluster, Search head cluster)
> CSPL-544: Automation for secret object update

- test/custom_resource_crud/custom_resource_crud_test.go
- test/secret/secret_test.go
- test/testenv/secretutil.go
- test/testenv/testenv.go
- test/testenv/verificationutils.go
Fixed the following issues with the secret test:
* GetSecretObject throwing parsing error on unmarshall. Modify the get secret command to get json string output that can be unmarshalled.
* Multiple Log.Info issues (Odd keys value pairs provided resulting in errors during runtime)
* No assertion in Verification methods ( Test are not failing on key mismatch)
* No Update Phase check after new secret are applied resulting in failures due to incorrect phase.
* Incorrect Secret response struct.
* Incorrect parameter names defined for method **VerifySecretObjectUpdate**
* Removed redundant phase check method ( Not related to secret test)
* Added support for verification for **password, idxc_support, pass4symmkey, shc_secret**
* Added proper checks for Splunk Environment to go to Ready Phase
> CSPL-931: Fix failing secret test

- pkg/splunk/enterprise/monitoringconsole.go
Resource requests and limits are added for MC based on below documentation:
1. https://www.splunk.com/pdfs/technical-briefs/deploying-splunk-enterprise-on-amazon-web-services-technical-brief.pdf
2. (c5.2xlarge) architecture req from https://aws.amazon.com/ec2/instance-types/c5/
> CSPL-555 Adding resource requests/limits for MC

- pkg/splunk/enterprise/monitoringconsole.go
Reverts splunk/splunk-operator#286
> Revert "CSPL-555 Adding resource requests/limits for MC"

- test/secret/secret_test.go
- test/testenv/deployment.go
- test/testenv/secretutil.go
- test/testenv/verificationutils.go
* S1 ( Standalone)
* Setup the Test SVA
* Delete the splunk secret object  / Delete Secret Data in Secret Object
* Verify a new splunk secret object is created
* Wait of Splunk Pods to recycle
* Verify new HEC token, admin password, idxc_secret, shc_secret, pass4SymmKey is present on the new versioned secret
* Verify new HEC token, admin password, idxc_secret, shc_secret, pass4SymmKey is mounted on the PODs
**Added delete only for Standalone as deleting the secrets leads to pod recycling which takes around 20-30 mins on C3 and M4**
```
[1] secret test
[1] /Users/tpereira/Git/splunk-operator/test/secret/secret_test.go:26
[1]   Multisite cluster deployment (M13 - Multisite indexer cluster, Search head cluster)
[1]   /Users/tpereira/Git/splunk-operator/test/secret/secret_test.go:299
[1] …
```
> Cspl 545: Secret object Delete scenario with standalone deployment

- test/licensemaster/lm_c3_test.go
- test/licensemaster/lm_m4_test.go
- test/licensemaster/lm_s1_test.go
- test/secret/secret_c3_test.go
- test/secret/secret_m4_test.go
- test/secret/secret_s1_test.go
- test/testenv/secretutil.go
- test/testenv/util.go
- test/testenv/verificationutils.go
- Added admin password verification to secret object update and delete cases
- Split Licensemaster test case's into individual files based on SVA
Note: Hec_token would also be verified as part of secret object update api access key. Will be added later
**Test Scenarios**: (SVA's covered: S1)
Delete secret data
Verify New versioned secret are created with correct value.
Verify new secrets are mounted on pods.
Verify old Secrets cannot be used for api access (password)
**Test Scenarios**: (SVA's covered: S1, C3, M4)
Update Secrets Data
Verify New versioned secret are created with correct value.
Verify new secrets are mounted on pods.
Verify New Secrets are present in server.conf 
Verify New updated Secrets via api access (password)
**Secret**
C3/M4 Modify
```
[2] • [SLOW TEST:1906.794 …
```
> CSPL-947: Added admin password verification on splunk instance

- test/deploy-eks-cluster.sh
- test/env.sh
CircleCI pipeline failing for EKS Cluster. 
* Changed Cluster name to circumvent cluster creation errors
* Changed authentication variable name for ECR Repository for eks cluster creation
> CSPL-955-changed-cluster-name

- test/deploy-eks-cluster.sh
EKS Cluster creation is failing on Circle CI due condition mismatch in following snippet :
```
found=$(eksctl get cluster --name "${CLUSTER_NAME}" )
if [ -z "${found}" ]; then
```
On Ubuntu `eksctl` has default verbose level of 3 which prints extra lines 
```
2021-04-09 16:06:21 [ℹ]  eksctl version 0.44.0
2021-04-09 16:06:21 [ℹ]  using region us-west-2
Error: unable to describe control plane "integration-test-cluster-eks": ResourceNotFoundException: No cluster found for name: integration-test-cluster-eks.
{
RespMetadata: {
StatusCode: 404,
RequestID: "3068b8e5-0286-4025-a226-7f8f5049e215"
},
Message_: "No cluster found for name: integration-test-cluster-eks."
}
```
This passes the `if` condition hence cluster is never created. 
However on setting the verbose level to 0 the `if` condition …
> CSPL-955: Verbose level change

- docs/Examples.md
- pkg/splunk/enterprise/configuration.go
The JIRA [CSPL-570](https://jira.splunk.com/browse/CSPL-570) points out that the License Master(LM) logs are not forwarded to the Cluster Master(CM) which is configured as a license slave. The reason for this is that the LM has not setup the **outputs.conf** to send to the CM via indexer discovery. To enable the same on the LM, we need to introduce the **clusterMasterRef** in the LM Spec as show in the example below:
```
apiVersion: enterprise.splunk.com/v1beta1
kind: LicenseMaster
metadata:
name: example
finalizers:
- enterprise.splunk.com/delete-pvc
spec:
clusterMasterRef:
name: example
volumes:
- name: licenses
configMap:
name: splunk-licenses
licenseUrl: /mnt/licenses/enterprise.lic
```
The operator uses the **clusterMasterRef** to introduce the env variable …
> CSPL-570 Documentation for configuring indexer clusters and standalones with LM

- test/deploy-eks-cluster.sh
- test/secret/secret_c3_test.go
- test/secret/secret_m4_test.go
- test/secret/secret_s1_test.go
- test/testenv/secretutil.go
- test/testenv/testenv.go
- test/testenv/verificationutils.go
Added Hec token verification to secret object update and delete cases
Fixed spell Error in Deploy EKS-Cluster.sh file
Delete secret data
Verify New versioned secret are created with correct value.
Verify new secrets are mounted on pods.
Verify Input.conf file has updated hec token
Verify old Secrets cannot be used for api access (hec_token)
Update Secrets Data
Verify New versioned secret are created with correct value.
Verify new secrets are mounted on pods.
Verify Input.conf file has updated hec token
Verify New updated Secrets via api access (hec_token)
S1
```
• [SLOW TEST:501.610 seconds]
[1] Secret Test for SVA S1
[1] /Users/tpereira/Git/splunk-operator/test/secret/secret_s1_test.go:26
[1]   Standalone deployment (S1) with LM
[1] …
```
> CSPL-948: Automation for hec token on splunk Instance

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
After upgrading operator-sdk to v0.18.2 the nightly builds started to fail due to https://github.com/kubernetes/kubernetes/issues/91395 which is an issue with how Kubernetes 1.18 interprets the operator-sdk v0.18.2 generated CRDs.
The issue manifests as :
"The CustomResourceDefinition “clustermasters.enterprise.splunk.com” is invalid: spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[serviceTemplate].properties[spec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property"
> Manually fix nightly build after Operator-SDK v0.18.2 upgrade

- test/licensemaster/lm_c3_test.go
- test/licensemaster/lm_m4_test.go
- test/licensemaster/lm_s1_test.go
- test/secret/secret_c3_test.go
- test/secret/secret_m4_test.go
- test/secret/secret_s1_test.go
- test/testenv/s3utils.go
* Created utility to create a s3 session
* Updated Utility to be able to download from S3
** Utility can now be used to download any generic file
* Created Utility to be able to upload file to S3
* Created Utility to delete file on S3
> CSPL-1027: Utility to download or upload file to s3

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1/common_types.go
- pkg/splunk/client/awss3client.go
- pkg/splunk/client/s3client.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/util/secrets.go
1.This PR targets framework, which will be used by operator to connect to remote storage(typically s3) to get the list of apps as specified in the CRs and which can be used later on to deploy and install the apps from remote storage.
2.This PR is the first part of the changes. Second part/PR will target UTs and code coverage for the related code.
> Initial commit for S3 framework APIs

- .circleci/config.yml
Reduced parallel test run to avoid nightly failure on eks cluster 
Changed cluster name for eks cluster to circumvent existing resource issue
> CSPL-1063-fix-nightly-run-failure

- test/testenv/util.go
Added common utils details below:
* Util to get directories under given path on a pod
* Util to check if a string exists in a given string slice
* Util to check two string slices match
Original PR with base develop https://github.com/splunk/splunk-operator/pull/353.
> CSPL-1068 added common util to support app framework test automation

- docs/README.md
- docs/SmartStore.md
Clarify in documentation how admins can setup additional Smartstore & Index configuration on top of the existing [CR method](https://splunk.github.io/splunk-operator/SmartStore.html) via Apps
See https://github.com/splunk/splunk-operator/issues/347
> CSPL-1082: Update Docs for Smartstore

- pkg/splunk/client/awss3client.go
- pkg/splunk/client/minioclient.go
- pkg/splunk/client/s3client.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- pkg/splunk/test/awss3client.go
- pkg/splunk/test/util.go
This is the part-2 PR for the original PR([PR#344](https://github.com/splunk/splunk-operator/pull/344)). It contains the following changes - 
1. A new framework for S3 Client for AWS for UTs.
2. Unit tests covering the mock client.
3. Introduction of `S3ClientMgr` to handle the retrieval of apps list from S3.
Additional changes - 
1. Fix the minio client to adhere to the new framework.
2. Minor fix in clustermaster.go and searchheadcluster.go to allow the scope of apps to be both local and cluster.
**NOTE:**
In future, if anyone wants to write a mock client(like for e.g. for minio client), then they can write a similar client which behaves the same way as MockAWSS3Client.
> CSPL-1065: Framework for mock client for AWS S3 and related unit tests

- pkg/splunk/client/awss3client.go
- pkg/splunk/controller/configmap.go
- pkg/splunk/controller/configmap_test.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/names.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- Added new configMap to update the latest apps status to the pod locations
> CSPL-767: Operator trigger Instance pod to download app package from S3

- test/monitoring_console/monitoring_console_test.go
- test/testenv/deployment.go
- test/testenv/util.go
- test/testenv/verificationutils.go
Added test to verify MC Pod comes up when MC CRD is applied.
Test Run
```
• [SLOW TEST:213.434 seconds]
Monitoring Console test
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/monitoring_console/monitoring_console_test.go:30
Deploy Monitoring Console
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/monitoring_console/monitoring_console_test.go:53
smoke, monitoring_console: can deploy MC CR
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/monitoring_console/monitoring_console_test.go:54
```
> Cspl 1055 test for mc crd

- pkg/splunk/enterprise/util.go
As part of the app installation framework for SOK, there is a requirement to install apps locally to CM/SHDeployer instances.  These apps would not be pushed to the SHC/IDC but rather only be installed on the CM.
Originally splunk-ansible did not have a method of installing apps locally on CM/Deployer instance.  Any apps specified in `apps_location` we pushed to the cluster and disabled locally.  However with https://github.com/splunk/splunk-ansible/pull/628 the `apps_location_local` allows apps listed here to be installed locally to CM/Deployer instances only.  The operator needs to use this new config for locally scoped apps on CM/Deployer instances.
Verify the new functionality of the operator and ansible changes while making sure if old splunk images (without the needed ansbile …
> CSPL-1108 Locally scoped app install from CM/Deployer

- deploy/role.yaml
Add a separator in deploy/roles.yaml
On applying the Splunk-operator-install.yml it should create the service account for the Splunk operator. Due to these separator lines missing in the roles.yml we saw the below difference Splunk-operator-install.yml due to which, when the Splunk operator is deployed on the fresh instance the service account was not getting created and hence the operator pod was not coming up.
Although the upgrade of the operator would have worked seamlessly as the service account for Splunk operator would pre-exist
Incorrect:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: splunk-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
```
Correct:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: splunk-operator
---
apiVersion: …
```
> CSPL-1115: Add a separator in deploy/roles.yaml

- test/c3/appframework/appframework_suite_test.go
- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_suite_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_suite_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/s3utils.go
- test/testenv/verificationutils.go
Update test cases for App-framework 
* Check apps are copied to respective directories
* Check install status on apps
* Check version on App
* Perform an re-poll
* Check new Apps are installed
> CSPL-1071: App installation validation for app framework

- docs/ChangeLog.md
the correct case is extraEnv NOT extraEnv
> doc: Correct change log extraEnv

- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_standalones_crd.yaml
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/util_test.go
This PR ensures the `GetNextRequeueTime` is read from the in-memory structure rather than what is specified in the CR. This is to avoid making use of invalid configs in the CR (which would have been validated & stored in memory)
> CSPL-1135: Fix a bug in GetNextRequeueTime where we should provide the polling interval from status

- pkg/splunk/enterprise/util.go
The app-list configmap only adds app that have changes since the last app install.  If there are no apps to add, the file is not written to the configmap.
However after https://github.com/splunk/splunk-operator/pull/378 the app_list_local.yml is being written empty due to the following check:
```
func ApplyAppListingConfigMap(client splcommon.ControllerClient, cr splcommon.Me
...
if localAppsConf != yamlConfHeader {
mapAppListing["app-list-local.yaml"] = localAppsConf
```
This causes differences in the Pod Volumes and Pod Env (namely SPLUNK_DEFAULTS_URL) which causes an additional (and unnecessary) pod restart after the Pod becomes ready from the initial (necessary) restart to install the app changes:
```
{"level":"info","ts":1624470956.0716994,"logger":"splunk.reconcile.MergePodUpdates"," …
```
> Fix unnecessary restarts due to empty app-list configmap after app update

- test/c3/appframework/appframework_suite_test.go
- test/c3/appframework/appframework_test.go
- test/licensemaster/lm_c3_test.go
- test/m4/appframework/appframework_suite_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_suite_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/verificationutils.go
Automation Covers:
Waiting for the polling interval for new downloads to trigger.
Check that Apps are updated or newer apps are installed
Passing Runs.  Failures not see after builds using https://github.com/splunk/splunk-operator/pull/390 
```
[2] • [SLOW TEST:453.295 seconds]
[2] s1appfw test
[2] /Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:30
[2]   appframework Standalone deployment (S1) with App Framework
[2]   /Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:63
[2]     s1, appframework: can deploy a standalone instance with App Framework enabled
[2]     /Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:64
[2] ------------------------------
[2] …
```
> CSPL-1114: Automation for Polling updates on App framework

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1/common_types.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/standalone_test.go
Do not enforce the checks for volume  'storageType' and 'provider', if the volume is used for Smartstore.
> cspl-1136: Storage type and provider config should be optional for Smartstore

- test/c3/appframework/appframework_test.go
- test/licensemaster/lm_c3_test.go
- test/m4/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/verificationutils.go
Fixed error in local install.
Added an Eventually check into app Folder check. 
Issue seen: 
1. Even after all pods are checked to be in ready state sometimes app install via bundle push lags behind by a few seconds.
Possible solutions:
- Check that bundle push is competed on all pods and then check app install state
- Loop for certain time to account for bundle push, to check that app is not installed(Implemented)
2.  Wrong variable  was passed to local app install check. Fixed
Passing runs:
```
• [SLOW TEST:2048.302 seconds]
m4appfw test
/Users/tpereira/Git/splunk-operator/test/m4/appframework/appframework_test.go:28
Multi Site Indexer Cluster with SHC (m4) with App Framework
/Users/tpereira/Git/splunk-operator/test/m4/appframework/appframework_test.go:62
integration, m4, appframework: …
```
> Fixes for pipeline failures

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_monitoringconsoles_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- pkg/apis/enterprise/v1/common_types.go
- pkg/apis/enterprise/v1/zz_generated.deepcopy.go
- pkg/controller/add_monitoringconsole.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/monitoringconsole_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
Full MC configuration/reconfiguration (All deployments other than IDC)
Example to create Standalone with mcRef 
```
apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
name: s2
finalizers:
- enterprise.splunk.com/delete-pvc
spec:
monitoringConsoleRef:
name: test
```
> CSPL-1044 Full MC configuration/reconfiguration (All deployments other than IDC)

- test/c3/appframework/appframework_test.go
- test/licensemaster/lm_c3_test.go
- test/m4/appframework/appframework_test.go
Added polling update for local app installation scenario.
Passing Runs: 
```
• [SLOW TEST:1406.771 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:28
Clustered deployment (C3 - clustered indexer, search head cluster)
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:159
c3, appframework: can deploy a C3 SVA and have apps installed locally on CM and SHC Deployer
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:160
{"level":"info","ts":1626119788.4379241,"msg":"testenv deleted.\n","testenv":"c3appfw-efk"}
{"level":"info","ts":1626119788.437949,"msg":"testenv deleted.\n","testenv":"c3appfw-efk"}
JUnit report was created: …
```
> CSPL-1146: Added polling update scenario for locally installation scenario

- pkg/splunk/client/awss3client.go
- pkg/splunk/client/minioclient.go
Make sure that secure connections are used when connection to the AppRepo volumes from the Splunk Operator.
Fix crash when using incorrect endpoint for aws client when using AppRepo volume config.
Use the http transport library and useSSL flags for the aws and minio client libraries respectively to enforce use of secure transport to the remote store 
Verify no crash on incorrect volume endpoint. 
Validate that apps can be downloaded and installed from remote store using secure transport.  Verify via operator logs:
```
{"level":"info","ts":1625183320.4624453,"logger":"splunk.client.InitAWSClientSession","msg":"AWS Client Session initialization successful.","region":"us-west-2","TLS Version":"TLS 1.2"}
{"level":"info","ts":1625183320.462464,"logger":"splunk.client.GetAppsList","msg":"Getting …
```
> CSPL-1157: Enforce TLS between Operator and AppRep

- test/c3/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
This PR adds the 2 following tests:
- C3 SVA: Installation of ES app from the deployer on the SHC (ES is first installed on the deployer, then in the /shcluster/apps folder and eventually bundle pushed to the SH)
- S1 SVA:  Installation of ES app locally on a standalone.
Note: It takes extra config in the spec to have ES installed correctly:
- Set the environment variable SPLUNK_ES_SSL_ENABLEMENT to 'ignore' to avoid the following error to show up in the logs: "FATAL: Error in 'essinstall' command: Automatic SSL enablement is not permitted on the deployer"
- Raise the values of Liveness and Readiness probes timeouts. ES takes a long time to get installed, default values are not sufficient. Once a timeout is reached, the deployer/standalone pod will restart and test will eventually fail. …
> Adding automation of ES app installation

- .circleci/config.yml
- test/deploy-cluster.sh
- test/deploy-eks-cluster.sh
- test/deploy-kind-cluster.sh
Enabled EKS cluster for app fw test
> Enabled EKS cluster for app fw test

- deploy/olm-catalog/splunk/1.0.2/splunk.v1.0.2.clusterserviceversion.yaml
- deploy/operator.yaml
- docs/ChangeLog.md
- docs/Images.md
- docs/README.md
Changing the Operator reference to 1.0.2 and and Splunk Enterprise ref to 8.2.1
> CSPL-1200: Version changes

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/verificationutils.go
Automation Changes
- Removed check for app installation on deployer and ClusterMaster
- Add check to see that apps are not downloaded in etc/apps in deployer and ClusterMaster
Test Results:
```
• [SLOW TEST:2671.113 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29
Single Site Indexer Cluster with SHC (C3) with App Framework
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:63
integration, c3, appframework: can deploy a C3 SVA with App Framework enabled
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:64
P [PENDING]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29
Clustered deployment (C3 - clustered …
```
> CSPL: Automation to check apps are not installed on deployer and ClusterMaster in ClusterWide Install

- deploy/olm-catalog/splunk/1.0.2/splunk.v1.0.2.clusterserviceversion.yaml
- deploy/operator.yaml
- docs/ChangeLog.md
- docs/Images.md
- docs/README.md
Update Splunk Enterprise docker image to include latest Ansible needed by 1.0.2 Operator version
> Image Update to 8.2.1-a1

- test/c3/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/deployment.go
Changes include:
- Commenting out liveness and Readiness from all app-framework test cases
- Uncomment out ESApp test case and set Install scope to 'clusterWithPreConfig'
> CSPL-1207: Remove liveness and readiness from App spec

- test/c3/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/s3utils.go
Changes:
- Changed scope on standalone to 'local' for ESapp
- Modified C3 Appframework test case to only install ESApp via clusterwithPreConfig Bucket
> Fix failures in pipeline run

- build/make_bundle.sh
- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_indexerclusters_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_standalones_crd.yaml
- deploy/olm-catalog/splunk/1.0.2/splunk.v1.0.2.clusterserviceversion.yaml
**Problem**
If we upgrade the operator from 1.0.1 to 1.0.2, the CRD version is also upgraded from v1 to v2. Now after the upgrade the `spec` section of the CRs(which were still on version v1) was pruned and pods either started crashing or they came up with no spec section at all.
This happened because of the default kubernetes behavior of pruning the unknown fields(fields that are not native to K8s server, such as the spec section of a CRD) of a CRD.
**Solution**
To fix this we had to add the field **x-kubernetes-preserve-unknown-fields: true** to older versions of the CRDs so that when  we upgrade to newer version/s, we still retain all the fields of the older versions.
> CSPL-1240: Fix the bug where during upgrade to latest CRD version, K8s server prunes the CRD fields

- .circleci/config.yml
- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/testenv/verificationutils.go
- Added additional logging for easier debugging
- Reduce App Framework Nightly parallel nodes to 2 to reduce flakiness
- Remove -stream for ginkgo test run for better log readability
> CSPL-1239: Added additional logging to app framework test for easier debugging

- test/monitoring_console/monitoring_console_test.go
Added additional phase check before verifying pods on MC.
> Added wait for MC to go to updating phase post SH scale up

- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- Once the MC CR is applied and has been configured with all the other instances whose CR has reference to the new MC, deleting the mcRef in the deployment's CR should make MC remove reference to that deployment
- Once the MC CR is applied and has been configured with all the other instances whose CR has reference to the new MC, changing the mcRef (from current MC to new) in the deployment's CR should make the current MC remove reference to that deployment, and new MC to configure the deployment
> [CSPL-1087] Full re-configuration when mcRef is changed/removed

- test/monitoring_console/monitoring_console_test.go
- test/testenv/mcutil.go
- test/testenv/testenv.go
- test/testenv/util.go
- test/testenv/verificationutils.go
Added Test for S1, C3, M4 test cases. 
1. Reconfigure S1 with 2nd Monitoring Console Name
2. Check 2nd Monitoring Console Config Map
3. Deploy 2nd Monitoring Console Pod
4. Verify S1 pod is configured on Monitoring Console Pod
5. Verify 1st Monitoring Console Config Map is not configured with S1
6. Verify 1st Monitoring Console Pod is not configured with S1
1. Reconfigure CM with Second MC
2. Verify CM in config map of Second MC
3. Create Second MC Pod
4. Verify Indexers in second MC Pod
5. Verify SHC not in second MC
6. Verify SHC still present in first MC d
7. Verify CM and Indexers not in first MC Pod
8. Configure SHC with Second MC
9. Verify CM, DEPLOYER, Search Heads in config map of seconds MC
10. Verify SHC in second MC pod
11. Verify Indexers in Second MC Pod
12. Verify CM and …
> MC Re-config Test Case

- deploy/olm-catalog/splunk/1.0.2/splunk.v1.0.2.clusterserviceversion.yaml
- docs/AppFramework.md
- pkg/controller/add_clustermaster.go
- pkg/controller/add_licensemaster.go
- pkg/controller/add_searchheadcluster.go
- pkg/controller/add_standalone.go
- pkg/splunk/controller/statefulset.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/names.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- pkg/splunk/test/controller.go
This PR targets the manual trigger for app update. Here are the key changes - 
1. Polling of app updates can be disabled by setting `appsRepoPollInterval=0`.
2. Now, all the CRs, with appFramework enabled, in the initial reconcile will either create a configMap(if not created) or will update the already existing configMap with the manual app update status for that CR and the refCount(i.e. the total number of CRs of that kind in the cluster in that namespace).
3. We can enable manual trigger for one time by editing the configMap and setting the `status` to `on` for that CR.
4. Once the checking for app update is done, we reset the status for that CR back to `off` again.
Here is how the configMap looks like for a ClusterMaster and a Standalone CR type - 
```
apiVersion: v1
data: …
```
> CSPL-1221: Manual trigger for app update

- .github/workflows/nightly-int-test-workflow.yml
* Modified int test workflow to run after every commit to develop and master branch 
* Added a new nightly int test workflow which runs on schedule.
> Added int test workflow and nightly workflows.

- .github/workflows/int-test-workflow.yml
- .github/workflows/nightly-int-test-workflow.yml
- test/monitoring_console/monitoring_console_test.go
Modified Monitoring Console test selection keyword to avoid cluster creation error on eks.
> Modify monitoring console selection name

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/testenv.go
- test/testenv/util.go
Added test cases for S1, C3, M4 with manual poll
Test Scenario:
- Setup config with app Framework enabled
- System downloads Initial list of apps and installs them
- Add new apps to  S3
- Set poll interval to 0 to disable polling
- Wait for 2 mins to confirm that no apps were downloaded/installed/updated
- Modify config map to trigger one time manual poll
- Wait for system to be in ready state
- Check pods for app install/update
Successful Run: 
```
[2] • [SLOW TEST:479.969 seconds]
[2] s1appfw test
[2] /Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:31
[2]   appframework Standalone deployment (S1) with App Framework
[2]   /Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:249
[2]     appfwint, s1, appframework: can deploy a …
```
> CSPL-1235: Manual poll for app framework Automation

- pkg/splunk/client/minioclient.go
- pkg/splunk/client/minioclient_test.go
When attempting to access a bucket on GCS (which is S3 compatable) the aws and minio clients both fail.  The aws client fails due to a missing region in the endpoint formatting.  The minio client init container fails to download anything and the app-listing configmap is malformed:
```
[splunk@splunk-gcp-test-standalone-0 splunk]$ cat /mnt/app-listing/app-list-local.yaml 
splunk:
app_paths_install:
default:
- "/init-apps/appframework1/application5.tgz"
- "/init-apps/appframework1/application5.tgz"
- "/init-apps/appframework1/application5.tgz"
- "/init-apps/appframework1/application5.tgz"
- "/init-apps/appframework1/application5.tgz"
- "/init-apps/appframework1/application5.tgz"
```
Fix the init container command so that there are no "//" in the path.
Fix the List API so that it doesn't use …
> [CSPL-1283] Fix AWS & minio S3 client code to support App framework on GCS

- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/util.go
When the App framework flow is in execution, re-entring the flow can cause the following issues:
1. For SHC, CR phase `Ready` doesn’t include the deployer, so, we should not mark the app deployment as complete. Right now, once the SHC becomes ready, we are marking the apps are deployed. So, if the AppSources are changing in between while the app installation is in progress, as the config Map is changing, we are marking all the apps as deployed, when some of them are not even installed: which needs to be fixed.
2. Even after the above case is fixed, still, the re-entrance is a problem, as the deployer Pod is ready, we are going to mark all the apps as deployed. On follow-up Pod reset if any app installation fails, our CR says all the apps are deployed, but that is not fully correct. This …
> CSPL-1316: Avoid app framework flow from re-entrancy

- .env
- .github/pre-release-workflow.yml
- build/make_bundle.sh
Added Pre Release workflow : 
- Creates a PR with all the changes needed for release. 
- Tags and push RC images
- Generates artifacts to be distributed to QA/Test Teams with RC image
> Automated pre release workflow

- test/s1/appframework/appframework_test.go
- test/testenv/deployment.go
- test/testenv/util.go
- test/testenv/verificationutils.go
* Create 2 App Sources for MC and Standalone
* Prepare Standalone CRD with MC and App config
* Apply Standalone CRD and wait for pod to become ready
* Prepare MC CRD with App Config
* Wait for MC to become READY
* Verify apps are copied, installed on MC AND Standalone Pod
* Upgrade apps in app sources
* Wait for MC and Standalone are READY
* Verify apps are copied, installed and upgraded on MC AND Standalone Pod
* Wait for Standalone and MC to be ready 
* Verify apps are copied, installed on MC AND Standalone Pod
* Wait for Standalone and MC to be ready 
* Verify apps are copied, installed on MC AND Standalone Pod
```• [SLOW TEST:1618.402 seconds]
s1appfw test
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/s1/appframework/appframework_test.go:30
appframework …
```
> CSPL-1226 S1 Automation for MC with App Framework

- build/make_bundle.sh
**Problem*
The command `make generate` would fail if there was no version change from previous version.
**Solution**
Add a check for version change in the script.
> CSPL-1339: Fix make_bundle.sh to check for version change

- .github/workflows/int-test-workflow.yml
- .github/workflows/nightly-int-test-workflow.yml
Added new image push with tag `int` to integration test workflow
Added checkout develop branch for nightly integration test.
> Modify int test workflow

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/cmutil.go
- Modified app upload logic to upload apps within each test case
- Added bundle push validation to missing c3 test case
Results
```
• [SLOW TEST:469.748 seconds]
s1appfw test
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:30
appframework Standalone deployment (S1) with App Framework
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:326
smoke, s1, appframework: can deploy a standalone instance with App Framework enabled and install around 350MB of apps at once
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:327
{"level":"info","ts":1634763939.235208,"msg":"testenv deleted.\n","testenv":"s1appfw-wep"}
JUnit report was created: …
```
> CSPL:1387 Modify app upload logic to selectively upload apps within test case

- pkg/splunk/enterprise/indexercluster.go
- test/m4/appframework/appframework_test.go
- test/monitoring_console/monitoring_console_test.go
IDXC fails to scale up when MC CR is deployed in the namespace with pre-existing IDXC.
**Problem Description:** 
Create the below scenario:
1. Create CM and Indexer Cluster
2. Create Monitoring Console Pod
3. Scale up the indexer cluster from 3 replicas to 4 replicas
Indxer Cluster CR will fail to scale up with the below error: 
```
{"level":"info","ts":1634179846.5632071,"logger":"splunk.enterprise.ApplyIdxcSecret","msg":"Namespaced scoped secret revision has changed","Desired replicas":4,"IdxcSecretChanged":[],"NamespaceSecretResourceVersion":"28455441","mock":false}
{"level":"error","ts":1634179846.6101015,"logger":"splunk.reconcile.Reconcile","msg":"Reconciliation requeued","Group":"enterprise.splunk.com","Version":"v3","Kind":"IndexerCluster","Namespace":"default","Name":"example-idxc …
```
> CSPL-1379 IDXC fails to scale up when MC CR is deployed with pre-existing IDXC

- test/c3/appframework/appframework_test.go
- test/custom_resource_crud/custom_resource_crud_c3_test.go
- test/custom_resource_crud/custom_resource_crud_m4_test.go
- test/custom_resource_crud/custom_resource_crud_s1_test.go
- test/delete_cr/deletecr_test.go
- test/ingest_search/ingest_search_test.go
- test/licensemanager/lm_c3_test.go
- test/licensemanager/lm_m4_test.go
- test/licensemanager/lm_s1_test.go
- test/scaling_test/scaling_test.go
- test/secret/secret_c3_test.go
- test/secret/secret_m4_test.go
- test/secret/secret_s1_test.go
- test/smoke/smoke_test.go
- test/testenv/deployment.go
- test/testenv/verificationutils.go
- CR Crud
- License Manager 
- Secret 
Dependent on PR: https://github.com/splunk/splunk-operator/pull/562
> CSPL-1438: Add missing mc test develop

- pkg/apis/enterprise/v2/common_types.go
- pkg/splunk/common/names.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
As a Splunk Operator Admin, I need the operator App framework scheduler to run a download worker job for copying and untarring(in case of cluster scoped apps) of any app packages that have been identified and new/updated so they can be installed on the Splunk Operator managed deployment.
Acceptance Criteria:
* If the download/install state of this CR is Ready then, call a new API which will do the following as part of each thread
Copy the App to Splunk Pod (init-apps) (if not already copied) - this is both for cluster & local scope
* For cluster-scope, Untar the copied App to respective destination (../etc/shcluster/apps/  OR ../etc/master-apps/)
* For local scope, no Untar as tarball is directly used for installation
* Update the state machine to correctly indicate the copy and untar …
> CSPL-1340: App framework - Add APIs to copy and untar app on Splunk pod and prune it on operator pod

- test/s1/appframework/appframework_test.go
* Redistributed test between smoke and int
* Added missing MC Ready Checks ( Updating apps while MC is not READY causes it to go in CrashLoopBackOff) 
* Added missing upload of apps 
* Corrected invalid verifications
Test passed 5 times. Running 3 test in parallel. 
```
can deploy a standalone instance with App Framework enabled and install around 350MB of apps at once
• [SLOW TEST:373.617 seconds]
s1appfw test
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/s1/appframework/appframework_test.go:30
Standalone deployment (S1) with App Framework
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/s1/appframework/appframework_test.go:661
integration, s1, appframework: can deploy a standalone instance with App Framework enabled and install around 350MB of …
```
> CSPL-1454: Fix s1 appframework test

- test/delete_cr/deletecr_test.go
- test/monitoring_console/monitoring_console_test.go
- test/scaling_test/scaling_test.go
- test/testenv/mcutil.go
Backport for PR : https://github.com/splunk/splunk-operator/pull/586
* Added test to integration pipeline. Removed references to MCPodReady
* Resolve mc flaky test
(cherry picked from commit e4e1c69148c60cafa541cc203f70d421217e8d99)
> CSPL-1443: Remove references to old MCPodReady function. (#586)

- test/m4/appframework/appframework_test.go
- test/testenv/deployment.go
- test/testenv/verificationutils.go
* Disabled Test Case 
* Incorrect use of verification methods
* Removed MC from Scaling Test as the scenario covered in monitoring console test suite
```
• Failure [2600.949 seconds]
c3appfw test
/home/runner/work/splunk-operator/splunk-operator/test/c3/appframework/appframework_test.go:29
Single Site Indexer Cluster with SHC (C3) with App Framework
/home/runner/work/splunk-operator/splunk-operator/test/c3/appframework/appframework_test.go:455
smoke, c3, appframework: can deploy a C3 SVA with App Framework enabled, install apps,scale up IDXC and SHC, install app on new pods, scale down [It]
/home/runner/work/splunk-operator/splunk-operator/test/c3/appframework/appframework_test.go:456
Timed out after 1500.001s.
Expected
<common.Phase>: 
to equal
<common.Phase>: Ready …
```
> CSPL-1468- Fix M4 Test case issues

- test/m4/appframework/appframework_test.go
- test/testenv/deployment.go
- test/testenv/verificationutils.go
(cherry picked from commit 39efbbc07ece446bc483b2372f405dc35054236b)
Backport for PR : https://github.com/splunk/splunk-operator/pull/588
Added additional changes needed to bring both test files in sync.
> Fix M4 Test case issues (#588)

- test/c3/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/deployment.go
- Added a common function to generate Appframwork spec for a specific CR
- Added different AppFramework sources for each CR(IDXC and SHC)
```
• [SLOW TEST:3489.669 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29
Single Site Indexer Cluster with SHC (C3) with App Framework
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:270
smoke, c3, appframework: can deploy a C3 SVA with App Framework enabled, install apps and downgrade them
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:271
• [SLOW TEST:834.511 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29
Clustered deployment (C3 - clustered indexer, …
```
> CSPL:1417 Added different app source per CR

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
- test/testenv/deployment.go
- test/testenv/s3utils.go
- test/testenv/util.go
- test/testenv/verificationutils.go
Improving logging for all App framework tests:
- Adding Test steps at the beginning of the tests which don't have it yet.
- Adding new logging messages before important steps
- Clarifying and reordering existing log messages, making clear which step is being done
- Standardise names over the tests (for ex, no 'CM' or 'cluster-master', only 'Cluster Manager' everywhere)
> CSPL-1414/CSPL-1415/CSPL-1416: Improve logging messages for all app framework tests

- test/s1/appframework/appframework_test.go
Changes:
- Use common utility to create app framework spec
Results
```
• [SLOW TEST:1017.280 seconds]
s1appfw test
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:30
Standalone deployment (S1) with App Framework
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:58
smoke, s1, appframework: can deploy a Standalone instance with App Framework enabled, install apps then upgrade them
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:59
• [SLOW TEST:924.507 seconds]
s1appfw test
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:30
Standalone deployment (S1) with App Framework
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go: …
```
> CSPL-1418: Use common utility to create appframework spec for S1

- test/m4/appframework/appframework_test.go
- test/testenv/deployment.go
Added different AppFramework sources for each CR(IDXC and SHC)
Passed tests:
[1] • [SLOW TEST:1660.371 seconds]
[1] m4appfw test
[1] /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:30
[1]   Multisite Indexer Cluster with Search Head Cluster (m4) with App Framework
[1]   /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:298
[1]     integration, m4, appframework: can deploy a M4 SVA with App Framework enabled, install apps and downgrade them
[1]     /Users/jambrosiano/splunk-operator/develop/splunk-operator/test/m4/appframework/appframework_test.go:299
[1] ------------------------------
[1] • [SLOW TEST:980.434 seconds]
[1] m4appfw test
[1] …
> CSPL-1419: use different App Source for every CR for M4 test cases

- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
When there are multiple CRs of the same/different Kind, each CR's App framework scheduler should have its own pipeline data structure to handle the app installations, while periodically yielding the reconciler.
Any operator-specific resources should be handled at the global level, and should not be tied to a particular CR. Right now, it is the amount of disk space available on the Operator Pod.
> CSPL-1507: App Framework scheduler should be unique/CR

- test/testenv/verificationutils.go
MC sometimes go to PENDING/UPDATING Phase after becoming ready. Added a workaround to ensure test dont fail because of this.
> Test workaround for cspl 1532

- .github/workflows/build-test-push-workflow.yml
- .github/workflows/int-test-workflow.yml
- .github/workflows/nightly-int-test-workflow.yml
- test/testenv/deployment.go
- test/testenv/testenv.go
- test/testenv/util.go
In case of test failure, the code in this PR will do the following during teardown:
- print the operator pod logs.
- Save the logs (from /opt/container_artifact/ansible.log) of every splunk instance pod  in the namespace in a separate file based on this pattern:
splunk-operator/test/test_artifacts/<namespace>/<deployment name>/<podname>.log
- Save these logs as artifacts when tests are run by github actions.
All artifacts are logged can be found in this run https://github.com/splunk/splunk-operator/actions/runs/1560923175
> CSPL-1278: Log additional debug information after a functional test fails

- deploy/cluster_role.yaml
Modify apiVersion in cluster_role.yaml to rbac.authorization.k8s.io/v1 (for compatibility with Kubernetes 1.22+)
> CSPL-1553: Modify apiVersion in cluster_role.yaml

- test/c3/appframework/appframework_test.go
Use different App sources for C3 test cases which install both local and cluster scoped apps:
Test results:
```
• [SLOW TEST:1112.040 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29
Clustered deployment (C3 - clustered indexer, search head cluster)
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:997
c3, integration, appframework: can deploy a C3 SVA with apps installed locally on Cluster Manager and Deployer, cluster-wide on Peers and Search Heads, then upgrade them
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:998
• [SLOW TEST:937.965 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:29 …
```
> Cspl 1525: Use different App sources for C3 test cases which install both local and cluster scoped apps

- pkg/apis/enterprise/v3/common_types.go
- pkg/splunk/controller/statefulset.go
- pkg/splunk/controller/statefulset_test.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
**Description**
In case of Standalone CR type, during scaling up, the new pods would not have the already installed apps that were installed on the existing pods.
**Solution**
During reconcile, at the moment when we decide if we are scaling up/down, update the AuxPhaseInfo for standalone CR, so that when afw scheduler runs, it knows to install apps for these new pods.
> CSPL-1169: Apps should be correctly installed on standalone pods when scaling up/down

- test/s1/appframework/appframework_test.go
- test/testenv/util.go
- test/testenv/verificationutils.go
Changes:
- Added a utility function to get the age of pods in namespace
- Added a validation function to compare age of pods with current age i.e validate if the pod had been reset
- Added pod reset check into S1 test cases.
> CSPL:1170 Check for pod reset on S1 due to app install via AppFramework

- pkg/controller/add_clustermaster.go
- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
**Problem Statement**
When we deploy a ClusterMaster along with any other CR such as SHC or Standalone with manual app update enabled(OR in other words, polling disabled), manual app update was not getting triggered when we changed the configMap to poll for the changes on the remote storage.
**Root Cause**
Because of a recent PR for merge from develop to feature branch, we reverted to the old code where ClusterMaster would not watch for changes in configMap. Because of this bug, any change in the manual app update configMap was not getting picked up by ClusterMaster.
**Solution**
1. Add configMap as a watch type to ClusterMaster CR.
2. Also enable in-tests related to manual app update in test/ folder.
> CSPL-1529: Fix a bug where ClusterMaster was not watching for changes in configMap

- docs/Examples.md
- pkg/apis/enterprise/v3/common_types.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
App framework Phase-2 leverages the Ansible to install APP packages.  As part of the Phase-3 app framework, Operator Pod downloads and copies the same to the Splunk Pod, and then installs the app package. This involves 3 different phases of the App framework scheduler that is introduced in the Phase-3 app framework.
To track these phases, there are new fields introduced as part of the App framework status. When the Operator is upgraded to the Phase-3 functionality, there needs to be migration logic to transition the phase-2 app framework status values into phase-3 compatible values.  
The code changes listed here address the migration logic needed.
```
appSrcDeployStatus:
ApsrcfullAps:
appDeploymentInfo:
- appName: Splunk_TA_aws-5.0.2.spl
deployStatus: 3
objectHash: …
```
> CSPL-1329: Migrate the Phase-2 App context status to Phase-3

- test/testenv/verificationutils.go
Removed Workaround introduced as part of this [PR-618](https://github.com/splunk/splunk-operator/pull/618) for CSPL-1532 (Fixed in PR#[646](https://github.com/splunk/splunk-operator/pull/646))
> CSPL-1536-removed-workaround-to-account-for-mc-reset

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/util.go
- test/testenv/verificationutils.go
* Refactored podlife method to use start time instead of alive time
* Modified `VerifyNoPodReset` to accept skip pod parameter
App Framework Smoke test are passing which use this method.
> Cspl 1574 refactor pod life method 

- pkg/apis/enterprise/v3/common_types.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- For standalone CR, auxPhaseInfo is always used irrespective of the replica configuration
- new fanOut flag, to create fan-out workers during the download phase
- some refactoring across the scheduler code
- Enabled the UT coverage for afwSchedulerEntry()
> CSPL-1494: Some misc improvements to AFW scheduler code

- pkg/splunk/client/minioclient.go
When using minio inside of a k8s cluster or in a network with other mitigations such as a cloud vpc with host to host network encryption use of TLS may be undesirable (double encryption) and can limit observability.
> fix: For Minio connections trust admin to pick protocol

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
Test Results:
```
• [SLOW TEST:605.259 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:30
Clustered deployment (C3 - clustered indexer, search head cluster)
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:2921
c3, integration, appframework: can deploy a C3 SVA with apps installed locally on Cluster Manager and Deployer, cluster-wide on Peers and Search Heads, then upgrade them via a manual poll
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:2922
{"level":"info","ts":1643565476.5501592,"msg":"testenv deleted.\n","testenv":"c3appfw-o25"}
{"level":"info","ts":1643565476.550236,"msg":"testenv deleted.\n","testenv":"c3appfw-o25"}
JUnit report was …
```
> CSPL-1539: Manual Poll test case when C3 & M4 are configured with both local and cluster scope

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
Automation scaling tests have been failing at VerifyNoPodReset as it was expected no pods at all to be reset, but actually the SHC pods would be reset after scaling.
This PR removes the SHC pods of the list of pod to be tested for no reset.
Tests run:
C3:
`[1] • [SLOW TEST:2393.876 seconds]
[1] c3appfw test
[1] /Users/jambrosiano/splunk-operator/CSPL-1620/splunk-operator/test/c3/appframework/appframework_test.go:30
[1]   Single Site Indexer Cluster with Search Head Cluster (C3) with App Framework
[1]   /Users/jambrosiano/splunk-operator/CSPL-1620/splunk-operator/test/c3/appframework/appframework_test.go:747
[1]     integration, c3, appframework: can deploy a C3 SVA with App Framework enabled, install apps, scale up clusters, install apps on new pods, scale down
[1] …
> CSPL-1620: Remove SHC pods from podReset verification for C3/M4 tests

- docs/AppFramework.md
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
When the Operator is not configured with an explicit volume mount,
use the '/tmp/appframework/' from main memory as the temporary staging area for the app package downloads.
> CSPL-1579: Temp AppFramework download location on Operator pod

- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/util/util.go
- pkg/splunk/util/util_test.go
- test/s1/appframework/appframework_test.go
**Problem**
Due to code cleanup for phase-2, we removed all the references of init-container and changed the directory(to temporarily store the apps to be installed) from "/init-apps/" to "/operator/appframework/<appSrcName>". In the latest code, operator would create the latter directory on the splunk pod/s. This worked fine for CRs with 1 pod. But for CRs like Standalone which can scale up to > 1 pods, it was an issue where we were not creating the directory structure required for staging the apps on splunk pod/s.
This eventually resulted in failure during PodCopy phase of app framework where operator was trying to copy the apps from operator pod to splunk pod/s.
**Solution**
Reset the `Stdin` field of the `streamoptions` data structure passed to the podExecClient, so that for each pod …
> CSPL-1639: Fix a bug where streamoptions needs to be reset for running same command on pods

- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/names.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/test/util.go
- pkg/splunk/util/util.go
Splunk volumes are set with the file permissions +660 by default. When an app
package(with their original file permissions) is included as part of a bundle push,
that app is deployed to the cluster members.  However, if there is a pod reset happens,
then all those apps are set with +660 values. Due to this permissions change, whenever
there is a next bundle push, it is  unnecessarily including those apps as part of the bundle
one more time.
Changes are made such that, always set the permissions to +660, before doing a bundle push,
that way the pod reset scenario will not include the apps(with just file permission changes)
that were already part of the last bundle push
> CSPL-1326: Update the File permissions for the cluster scoped apps

- .env
- .github/workflows/automated-release-workflow.yml
- .github/workflows/build-test-push-workflow.yml
- .github/workflows/int-test-workflow.yml
- .github/workflows/merge-develop-to-master-workflow.yml
- .github/workflows/nightly-int-test-workflow.yml
- .github/workflows/pre-release-workflow.yml
- Replaces 3rd party github tags with the git commit sha.
- Moved AWS CLI URL into the env file
- Replace keyword `licensemaster` with `licensemanager` in workflow files to align with bias language change in test cases.
> CSPL-1636: Replace tag for 3rd party github actions with the SHA

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
After CSPL-1633 refactoring got merged, test 'can deploy a C3 SVA with App Framework enabled for manual update' started to fail. This wasn't discovered before as this test was commented in the PR.
Reason of failure was  the bundle push test inside new AppFrameWorkVerifications method on line 1571 would fail as apps are not updated yet at that point. Fix is switching to just use 'VerifyAppInstalled' instrad, as we just want to verify app version here.
A later point of failure would have been in the end of the test with the last use of AppFrameWorkVerifications, as appVersion was still set to 'V1' at that time, so a line to set it correctly to 'V2' is added there also.
Last change is use of the correct replicas variable on line 1516 (shReplicas for SHC)
Same changes for the equivalent M4 …
> CSPL-1633: Fixing failing test 'can deploy a C3 SVA with App Framework enabled for manual update'

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/testenv/appframework_utils.go
Fixing failing app framework tests which have been refactored in CSPL-1633 but were commented out then:
For "can deploy a C3 SVA and have apps installed and updated locally on Cluster Manager and Deployer for manual polling" and "can deploy a M4 SVA and have apps installed and updated locally on Cluster Manager and Deployer via manual poll" , CrAppScope was incorrectly set to cluster instead of local
For "can deploy a C3 SVA with apps installed locally on Cluster Manager and Deployer, cluster-wide on Peers and Search Heads, then upgrade them via a manual poll" and "can deploy a m4 SVA with apps installed locally on Cluster Manager and Deployer, cluster-wide on Peers and Search Heads, then upgrade them via a manual poll" , some variables were incorrectly set
Passed runs:
[2] • [SLOW …
> CSPL-1666: correct install scope for apps in manual poll integration tests

- README.md
- docs/Install.md
- docs/README.md
- docs/SplunkOperatorUpgrade.md
- docs/Upgrade.md
- tools/upgrade-to-1.1.0.sh
This PR is for upgrade steps from 1.0.5 to 1.1.0. upgrade script takes 2 parameter,
-  current splunk installation namespace 
- splunk operator 1.1.0 manifest file path
` upgrade-to-1.1.0.sh --current_namespace=namespace1 manifest_file=release-v1.1.0/splunk-operator-cluster.yaml`
in the above example older operator was installed in `namespace1` namespace, so it takes the backup of the files first and then deleted all the older resources and installs the new operator in `splunk-operator `namespace. by default operator will be installed clusterwide. if user wants to watch specific namespace edit `config-map` `splunk-operator-config` in `splunk-opertao`r namespace, set `WATCH_NAMESPACE` field to the namespace operator need to watch
> CSPL-1606: Upgrade from 1.0.5 to 1.1.0 script and documentation

- deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
- deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
- deploy/crds/enterprise.splunk.com_monitoringconsoles_crd.yaml
- deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
- deploy/crds/enterprise.splunk.com_standalones_crd.yaml
- docs/AppFramework.md
- pkg/apis/enterprise/v3/common_types.go
- pkg/splunk/client/awss3client.go
- pkg/splunk/client/awss3client_test.go
- pkg/splunk/client/minioclient.go
- pkg/splunk/client/minioclient_test.go
- pkg/splunk/client/s3client.go
- pkg/splunk/client/util.go
- pkg/splunk/client/util_test.go
- pkg/splunk/enterprise/util.go
- test/c3/appframework/appframework_test.go
- test/licensemanager/lm_c3_test.go
- test/m4/appframework/appframework_test.go
- test/smartstore/smartstore_test.go
- test/testenv/appframework_utils.go
- test/testenv/remote_index_utils.go
**Problem**
Because of the issue mentioned [here](https://github.com/splunk/splunk-operator/issues/655), we were not able to pass in the region for a S3 compatible storage other than AWS and hence it would pass empty value as region.
**Solution**
Add `region` field as part of volume spec so that users can directly specify the region irrespective of the remote storage they are using.
> CSPL-1670: Add region as a configurable parameter in volume spec

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/util.go
- test/testenv/verificationutils.go
S1, C3, M4 automation test covering the following cases:
(install phase - operator reset):
- Create and apply a CR Spec with App Source containing 10 Apps 
- Wait for app installation to start 
- Kill the operator pod while app framework is in Install phase
- Wait for Operator Pod to come back up 
- Verify apps are installed correctly
(Download phase - operator reset):
- Create and apply a CR Spec with App Source containing 10 Apps 
- Wait for app installation to start 
- Kill the operator pod while app framework is in Install phase
- Wait for Operator Pod to come back up 
- Verify apps are installed correctly
INT test pass run: https://github.com/splunk/splunk-operator/actions/runs/2022325652.
> CSPL-1593: Add test where operator is reset while app install is in progress

- LICENSE
Updated license file for 1.1.0 release. Please refer [confluence page](https://splunk.atlassian.net/wiki/spaces/PROD/pages/313937142179/Third+Party+Software+Tracking)  for more details.
> Updated license file for 1.1.0 release

- pkg/splunk/enterprise/clustermaster.go
The [PR](https://github.com/splunk/splunk-operator/pull/723) for enterpriseApi changes introduced a [bug](https://github.com/splunk/splunk-operator/pull/723/files#r853401204) where wrong parameters are passed in **clustermaster.go** for the function setupInitContainer i.e image vs imagePullPolicy.
> CSPL-1737: Smartstore init container fails to initialize due to incorrect imagePullPolicy

- .github/workflows/int-test-workflow.yml
- test/s1/appframework/appframework_test.go
There was an issue with upgrading apps on new scaled-up standalone replicas
This test will compare ObjectHash of apps before and after upgrade to be sure update went well after scaling up
> CSPL-1589: Apps upgrade issue when having several standalone replicas

- test/smartstore/smartstore_test.go
Updated code to get correct name for s3 secret in smartstore test cases.
> CSPL-1742: Updated code to get correct name for s3 secret name

- test/c3/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
a test case with the following -
- Use random credentials
- Attempt Install an app from remote store, expect it to fail
- Change remote store credentials  to a new valid set
- Install a new app or update existing app from remote store, expect it to pass
Clean Run: https://github.com/splunk/splunk-operator/runs/6103552270?check_suite_focus=true
> CSPL 1218: App framework authentication tests

- docs/CustomResources.md
Docs change to fix github [issue](https://github.com/splunk/splunk-operator/issues/761) involving `remotePath` in smartstore defaults config
> CSPL-1762 - Remove remotepath docs example in defaults

- docs/Ingress.md
Fixing github [issue](https://github.com/splunk/splunk-operator/issues/771) for broken link in nginx docs
> CSPL-1767 - Nginx broken link

- config/manager/manager.yaml
Adding an annotation to define a default container for the operator deployment pod. Addressing github enhancement [request](https://github.com/splunk/splunk-operator/issues/765)
> CSPL- 1768 - Adding an annotation to define a default container

- test/m4/appframework/appframework_test.go
Adding test of manual polling doing these steps:
- Deploy M4 SVA with app source containing several apps, and AppsRepoPollInterval=0 to have manual polling
- Ensure the manual poll configMap splunk-namespace-manual-app-update has been created, apps have been installed.
- Add newer versions of apps in app source.
- Disable Manual polling by setting AppsRepoPollInterva>0, and setting back status to ON in config map.
- Verify manual polling has not been triggered in the next few seconds and apps not updated.
- Verify apps are eventually updated after the end of AppsRepoPollInterval.
> CSPL-1601: Manual Polling

- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_test.go
S1, C3, M4 automation test covering the following case:
- Create and apply CR Spec with App Source containing several apps 
- Wait for app download to Operator Pod to finish
- Add new version of apps to the apps source
- Verify all apps are installed in their original version 
- Verify app update shouldn't start before all original version of apps are installed
- Verify apps are eventually updated correctly
Clean Int-test-run: https://github.com/splunk/splunk-operator/actions/runs/2223037406
> CSPL-1596: Update apps on app source while installation is going on

- pkg/splunk/enterprise/util.go
Irrespective of the polling type, always update the LastAppInfoCheckTime,
so that, the LastAppInfoCheckTime can be used across the manual and periodic
polling switches
> CSPL-1770: Always update the last LastAppInfoCheckTime

- .github/workflows/automated-release-workflow.yml
- Makefile
- config/default/kustomization-cluster.yaml
- config/default/kustomization-namespace.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
- docs/Install.md
Now there will 2 different manifest files generated for release. (as earlier)
1. namespace scoped - `splunk-operator-install.yaml`
2. cluster scoped - `splunk-operator-cluster.yaml`
> CSPL-1727: Manifest files to differentiate namespace scoped and cluster scoped

- test/c3/appframework/appframework_suite_test.go
- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_suite_test.go
- test/m4/appframework/appframework_test.go
- test/s1/appframework/appframework_suite_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/appframework_utils.go
Test added to S1,C3 and M4 SVA of insufficient disk space on operator PV.
By default, Operator PV size is 1GB, so S1 test download 15 100MB-size apps in parallel and verifies all apps are eventually installed. For C3 and M4, it's 15 apps for Indexer Cluster and 15 for Search Head Cluster.
> CSPL-1600: Insufficient disk space on operator PV

- .github/workflows/build-test-push-workflow.yml
- .github/workflows/int-test-workflow.yml
- .github/workflows/nightly-int-test-workflow.yml
- Makefile
- test/c3/appframework/appframework_test.go
- test/m4/appframework/appframework_test.go
- test/run-tests.sh
- test/testenv/util.go
SHA Digest will be created based on check-in commit id.
run all smoke and integration test to above image
use the same image for clair vulnerability testing.
Clean run: https://github.com/splunk/splunk-operator/actions/runs/2343462619
> [CSPL-1735] integration workflow changes with git checkin image to appframework

- pkg/splunk/client/awss3client.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/util.go
This issue is most likely never exposed, but it can cause the Operator to crash under certain conditions. 
The third parameter for `scopedLog.Error()` should be a set of Key and values, as per the function declaration:
**go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:261**
```
func (l Logger) Error(err error, msg string, keysAndValues ...interface{}) {
}
```
When only one value is passed we can hit this crash for `odd number of arguments passed as key-value pairs for logging`
```
1.652302394894617e+09	DPANIC	controller.indexercluster.indexerClusterPodManager.getClusterManagerClient odd number of arguments passed as key-value pairs for logging	{"reconciler group": "enterprise.splunk.com", "reconciler kind": "IndexerCluster", "name": "example-idc", "namespace": "default", "ignored key": …
```
> CSPL-1801 - Avoid odd number of arguments passed for logging

- controllers/clustermaster_controller.go
- controllers/indexercluster_controller.go
- controllers/licensemaster_controller.go
- controllers/monitoringconsole_controller.go
- controllers/searchheadcluster_controller.go
- controllers/standalone_controller.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/clustermaster_test.go
- pkg/splunk/enterprise/finalizers_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/licensemaster_test.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/monitoringconsole_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/types.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- pkg/splunk/test/controller.go
On a reconcile entry, there is a possibility that the CR is cached(may not be
the latest). In such cases, CR status update fails, as the resource version
already changed.
Fix is made such that:
1. Always fetch the latest CR, then make the status update to avoid any update failures
2. Make sure that the cached CR is reflecting the latest, before yielding from current reconcile
so that the next reconcile has the latet status info to work with
> CSPL-1752: Do not update status on cached CR

- .github/workflows/int-test-workflow.yml
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
when we move from 8.2.6 to 9.0.0 , due to [enterprise issue](https://splunk.atlassian.net/browse/SPL-223386?jql=text%20~%20%22The%20downloaded%20bun[…]ecksum%20doesn%27t%20match%20the%20activeBundleChecksum%22](https://splunk.atlassian.net/browse/SPL-223386?jql=text%20~%20%22The%20downloaded%20bundle%20checksum%20doesn%27t%20match%20the%20activeBundleChecksum%22) migration fails for indexer cluster. In Operator code migration fails as we try to decommission the indexer. 
Fix: delete the indexer statefulset if container image version is different than statefulset image version
> Draft: cspl 1880: delete stateful set when image version differs

- Makefile
The current order of artifact generation can leave the remaining `config/default/kustomization.yaml` set to only watch namespaces after execution, which is not the default. This Task aims at fixing the order of generation in the Makefile to ensure the default value remains after execution.
> CSPL-1916 - Update Makefile to ensure correct order in artifact generation

- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
Changes for the operator app framework accept the Azure Blob as a valid remote storage provider.
- validate azure is a valid provider 
- validate that blob is a valid storage type
> CSPL-1922: Allow azure blob as valid data provider and remote storage type

- helm-chart/splunk-enterprise/.helmignore
- helm-chart/splunk-enterprise/Chart.yaml
- helm-chart/splunk-enterprise/templates/_helpers.tpl
- helm-chart/splunk-enterprise/templates/enterprise_v3_clustermaster.yaml
- helm-chart/splunk-enterprise/templates/enterprise_v3_indexercluster.yaml
- helm-chart/splunk-enterprise/templates/enterprise_v3_licensemaster.yaml
- helm-chart/splunk-enterprise/templates/enterprise_v3_monitoringconsole.yaml
- helm-chart/splunk-enterprise/templates/enterprise_v3_searchheadcluster.yaml
- helm-chart/splunk-enterprise/templates/enterprise_v3_standalone.yaml
- helm-chart/splunk-enterprise/values.yaml
Helm chart implementation of Splunk Instance as a separate chart from Operator.
Splunk Instance Chart to deploy a supported instance of Splunk managed by an Operator
- Standalone
- Cluster Manager
- Indexer Cluster
- Search Head Cluster
- Monitoring Console
- License Manager
> CSPL-1874: Helm chart support for all Splunk Instance types

- config/manager/kustomization.yaml
- pkg/splunk/client/azureblobclient.go
- pkg/splunk/client/azureblobclient_test.go
- pkg/splunk/client/names.go
- pkg/splunk/client/util.go
**Adding functionality to download app packages from Azure blob**
Changes related to CSPL-1923:
Extending  `azureblobclient.go` to allow downloading app packages from azure blob containers (buckets) 
Extending the unit tests to tests the download functionality as well as enhance the app lists unit tests
> CSPL-1923: Addition of code and unittests to download the app packages

- tools/k8_probes/livenessProbe.sh
Cases like the Splunk instance decommissioning, or when the Splunk is coming up with large number of indexs, existing liveness may fail, as the mgmt port may be busy.
Changes are made such that the liveness level may be reduced during the maintenance activity, so that the Pod will not be reset due to the liveness probe failure
> CSPL-1981: Add a lightweight liveness probe

- Makefile
- api/v4/common_types.go
- bundle/manifests/enterprise.splunk.com_clustermanagers.yaml
- bundle/manifests/enterprise.splunk.com_clustermasters.yaml
- bundle/manifests/enterprise.splunk.com_indexerclusters.yaml
- bundle/manifests/enterprise.splunk.com_licensemanagers.yaml
- bundle/manifests/enterprise.splunk.com_licensemasters.yaml
- bundle/manifests/enterprise.splunk.com_monitoringconsoles.yaml
- bundle/manifests/enterprise.splunk.com_searchheadclusters.yaml
- bundle/manifests/enterprise.splunk.com_standalones.yaml
- bundle/manifests/splunk-operator.clusterserviceversion.yaml
- config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
- config/crd/bases/enterprise.splunk.com_clustermasters.yaml
- config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
- config/crd/bases/enterprise.splunk.com_licensemasters.yaml
- config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
- config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
- config/crd/bases/enterprise.splunk.com_standalones.yaml
- config/manifests/bases/splunk-operator.clusterserviceversion.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_clustermanagers.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_clustermasters.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_indexerclusters.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_licensemanagers.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_licensemasters.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_monitoringconsoles.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_searchheadclusters.yaml
- helm-chart/splunk-operator/crds/enterprise.splunk.com_standalones.yaml
Related Jira tasks:
[**CSPL-2065**](https://splunk.atlassian.net/browse/CSPL-2065)
The comments on `common_types.go` need to include Azure blob along side AWS and Minio.
Run the `make bundle` command to update the CRDs for including Azure blob-related comments
[**CSPL-2066**](https://splunk.atlassian.net/browse/CSPL-2065)
While working on [CSPL-2065](https://splunk.atlassian.net/browse/CSPL-2065), it was noticed that the `make bundle` command generates the crd files under the `bundle/manifest` and `config/crd/bases` folders. However, the generated crd files need to be copied manually to `helm-chart/splunk-operator/crds` folder. In this task, the Makefile is changed so the `make bundle` target automatically copies the generated crd files to Helm chart folders.
> CSPL-2065, CSPL-2066 -update common types comments for azure blob

- test/run-tests.sh
Fixed false positives in int test by removing cleanup logic from run-test.sh 
This was removed earlier as well. 
The cleanup is taken care of in workflow steps.
> CSPL-2080 Fix false positive in int test

- test/c3/appframework/appframework_test.go
- test/c3/appframework/manager_appframework_test.go
- test/licensemanager/lm_s1_test.go
- test/licensemaster/lm_s1_test.go
- test/m4/appframework/appframework_test.go
- test/m4/appframework/manager_appframework_test.go
- test/s1/appframework/appframework_test.go
- test/testenv/testenv.go
- test/testenv/util.go
- test/testenv/verificationutils.go
Added checks for Liveness and Readiness scripts and config map across all pods
Scenarios added per SVA:
Check for readiness script and liveness script in all pods in Operator.
Check for probe config map
Check for probe config map recreated when pods are scaled up
Check for probe config map recreated when pod is deleted
> CSPL-2023: Added assertion for readiness and liveness script

- pkg/splunk/client/azureblobclient.go
- pkg/splunk/client/azureblobclient_test.go
Updated the error messages handling to log more detailed error message when the operator fails to fetch apps packages or download app packages due to _authorization not correct_ 
**Handles the following scenarios:**
**1. IAM scenario**
1.1. Managed identity is **not** configured for the AKS cluster
1.2. Managed identity is configured but it is not given permission to access the buckets/app packages
**2. Shared Access Key error handling**
2.1 Incorrect shared access key used (key in secretRef not matching with key in the azure blob storage account)
Added the necessary unit tests
> CSPL-2092: have better error message when authorization fails

- .github/workflows/int-test-workflow.yml
- Makefile
- test/monitoring_console/monitoring_console_test.go
- test/testenv/deployment.go
- Added new method for creation of M4 with Clustermaster CRD
- Update test to use the new method
Test failing because we were deploying manager and waiting for master to come up. 
Local Passing Run
```	{"testcaseenv": "mastermc-rqq-n9v"}
• [SLOW TEST:1392.361 seconds]
Monitoring Console test
/Users/pdhanoya/splunk-operator-git/splunk-livliness-probe/splunk-operator/test/monitoring_console/monitoring_console_test.go:31
Multisite Clustered deployment (M4 - 3 Site clustered indexer, search head cluster)
/Users/pdhanoya/splunk-operator-git/splunk-livliness-probe/splunk-operator/test/monitoring_console/monitoring_console_test.go:448
mastermc, integration, testrun: MC can configure SHC, indexer instances and reconfigure Cluster Manager to new Monitoring Console …
```
> CSPL-2103: Fix int test on develop

- tools/k8_probes/livenessProbe.sh
The liveness probe was failing in AKS pods. This PR is to enhance the step that extracts the splunkd process id from `ps` command.
Verified that the SHC pods are no longer restarting after this fix.
> CSPL-2109: Fine tune command to get splunkd pid as it fails in AKS linux box

- pkg/splunk/util/messages.go
- pkg/splunk/util/util.go
- pkg/splunk/util/util_test.go
While installing es, we get this message in stderr that needs to be suppressed as it is not an error
INFO: Installation complete\nINFO: SSL enablement set to ignore, continuing...\n"
@Twain Pereira / @Arjun Kondur
> CSPL-2168: Ignore a ES install info stderr message in installation 

- pkg/splunk/controller/statefulset.go
- pkg/splunk/controller/statefulset_test.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/clustermanager.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/finalizers_test.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
- pkg/splunk/enterprise/licensemanager.go
- pkg/splunk/enterprise/licensemanager_test.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/monitoringconsole_test.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/standalone_test.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
- pkg/splunk/test/controller.go
Changes are two fold:
1. Delete unnecessary owner references on the statefulSet in a CR during deletion. Retain the owner references to the CR only, delete rest.
2. On ClusterManager deletion, check if any other CR is holding a `clusterManagerRef` to it and wait till those are deleted/spec change to run the finalizer on the ClusterManager. This way, we retain the ClusterManager statefulSet until no other CR has a reference to it.
> CSPL-2151 - Changes to delete owner references of statefulSet on CR deletion, check for stale references to CM

- api/v4/common_types.go
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
CSPL-2167 - make essinstall default ssl_enablement flag as strict to adhere with splunk doc
https://docs.splunk.com/Documentation/ES/7.0.2/Install/InstallEnterpriseSecuritySHC#Installing_Splunk_Enterprise_Security_from_the_command_line_in_a_search_head_cluster_environment
> CSPL-2167 - Make strict flag as default flag for essinstall

- api/v4/common_types.go
- config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
- config/crd/bases/enterprise.splunk.com_clustermasters.yaml
- config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
- config/crd/bases/enterprise.splunk.com_licensemasters.yaml
- config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
- config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
- config/crd/bases/enterprise.splunk.com_standalones.yaml
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/clustermanager.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
- pkg/splunk/enterprise/licensemanager.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/monitoringconsole.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/util/messages.go
- pkg/splunk/util/util.go
- pkg/splunk/util/util_test.go
**Problem:**
As part of ES install operator executes following steps:
1. Download ES
2. Install ES app (extract to deployer apps directory)
3. Remove ES package from operator and deployer staging directory
4. Run ES post install commands like essinstall
What we saw that if step 4 fails, then Operator tries to install ES app again with following steps:
1. installAppAndCleanup is called which tries to find the app package on deployer (pod)
2. app package is not found and operator errors out.
**Solution:**
Broke down the installAppandCleanup method to separate methods install and cleanup called before and after post install.
> CSPL-2172 - Fix es install fail scenario

- Dockerfile
- Makefile
- config/rbac/kustomization-cluster.yaml
- config/rbac/kustomization-namespace.yaml
- docs/SplunkOperatorUpgrade.md
- fix for vulnerability in base os image
- fix for namespace specific manifest file generation
tested both the fixes they both work on openshift cluster
Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>
> cspl-2177: added dockefile changes to fix CVE-2022-42898 vulnerability 

- api/v4/common_types.go
- config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
- config/crd/bases/enterprise.splunk.com_clustermasters.yaml
- config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
- config/crd/bases/enterprise.splunk.com_licensemasters.yaml
- config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
- config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
- config/crd/bases/enterprise.splunk.com_standalones.yaml
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
**Problem:**
As part of ES install in SHC, the operator executes the following steps:
1. Download ES
2. Install the ES app (`splunk install app <download_dir_on_pod>/splunk-enterprise-security_xxx.spl`)
3. Run ES post install commands `essinstall`
4. Cleanup the app archive
What we saw is that if step 3 fails, then the Operator Install worker thread tries run step 2 again that is -  install the ES app again with command `splunk install app <download_dir_on_pod>/splunk-enterprise-security_xxx.spl`
In this case, the App install command comes back with an error: `\nApp \"SplunkEnterpriseSecuritySuite\" already exists; use the \"update\" argument to install anyway\n", "err": "command terminated with exit code 22"`
This error comes back because the install worker thread does not know about the …
> CSPL-2178: es post install failure should not trigger update of app install

- api/v4/common_types.go
- config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
- config/crd/bases/enterprise.splunk.com_clustermasters.yaml
- config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
- config/crd/bases/enterprise.splunk.com_licensemasters.yaml
- config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
- config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
- config/crd/bases/enterprise.splunk.com_standalones.yaml
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/configuration.go
- pkg/splunk/enterprise/configuration_test.go
Per the security requirements, reverting splunk/splunk-operator#1006 . Making strict as default again.
> Revert "CSPL-2187 - Make ssl_enablement ignore as default, disable strict for shc"

- test/appframework_az/c3/manager_appframework_azure_test.go
Test was failing as it was using ClusterMasterRef instead of ClusterManagerRef
> CSPL-2223: Fix C3 test failure on Azure

- pkg/splunk/controller/util.go
- pkg/splunk/enterprise/configuration.go
Default value for FailureThreshold not being set forces unnecessary statefulSet updates
> Fix faulty default FailureTreshold values

- docs/README.md
Fix [documentation](https://github.com/splunk/splunk-operator/tree/main/docs#splunk-apps-installation) which indicated ES being unsupported.
> Fix documentation which indicated ES being unsupported

- pkg/splunk/client/awss3client.go
Fix logging crash in AWS Client download app
> CSPL-2267 - Fix logging crash in AWS Client download app

- helm-chart/splunk-enterprise/templates/extra-manifests.yaml
- helm-chart/splunk-enterprise/values.yaml
- helm-chart/splunk-operator/templates/extra-manifests.yaml
- helm-chart/splunk-operator/values.yaml
hi @vivekr-splunk @gaurav-splunk @pdhanoya-splunk @tpereirasplunk 
the [operator documentation provides references to istio and nginx ingress](https://github.com/splunk/splunk-operator/blob/11b9ed2b7e6dfbf63b69f720e94e9880d7fa5fe8/docs/Ingress.md) resources, but the helm chart provides no interface to create these resources.
this PR makes use of a flexible and [commonly-used](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/extra-manifests.yaml) pattern to create arbitrary k8s resources. use cases include the above and things like
- grafana dashboards
- prometheus configuration
- alertmanager rules
- additional k8s service accounts
- k8s [external secrets](https://github.com/external-secrets/external-secrets) objects
- configmaps for secret injection via …
> chore: allow creation of additional arbitrary k8s manifests

- .github/workflows/helm-test-workflow.yml
only for main branch we need to run release helm workflow. instead of using helm chart directory to run test it will use github.io hosted splunk operator helm charts.
this can only be tested on main branch.
> adding add repo for main branch in pipeline test

- api/v4/common_types.go
- docs/Helm.md
- docs/SmartStore.md
Splunk Operator via the smartstore feature, sets the repFactor to auto in the [default] stanza of the splunk-operator app in order to help with the requirements [here](https://docs.splunk.com/Documentation/Splunk/9.0.4/Indexer/ConfigureSmartStore). This setting was applied to all indexes except for certain internal indexes such as metrics, introspection, telemetry, _metrics_rollup, _configtracker which have specific stanzas in the _cluster app with repFactor as 0.
Modifying the documentation to:
- Inform the Splunk Admin of repFactor being set to `0` by default and a solution to override it. 
- Inform the Splunk Admin that the SmartStore method is still usable if they prefer not set their keys on S3 buckets.(To be changed with OIDC)
> CSPL-2304 - Modify smartstore documentation for repFactor in internal indexes

- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/indexercluster_test.go
This PR test GITHUT -1153 issue
addresses issue https://github.com/splunk/splunk-operator/issues/1151.
There are 2 changes:
Make sure that the fix of PR https://github.com/splunk/splunk-operator/pull/1041 is applied in the cluster-manager usecase
Fix the check on the image version. The format of the image field being like splunk/splunk-operator:8.2.0, it is needed to get the version that is after the colon. The previous check was only checking if the image was starting with 8 or 9, which is always false.
> Cspl-2489: GITHUG-1153 - Fix indexer deletion in upgrade scenario

- pkg/splunk/enterprise/configuration.go
Operator 2.5.2, Standalone with the following config with cluster scope crashes operator:
```
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
name: ido
finalizers:
- enterprise.splunk.com/delete-pvc
spec:
replicas: 1
appRepo:
appsRepoPollIntervalSeconds: 900
defaults:
volumeName: volume_app_repo_us
scope: cluster
appSources:
- name: cspl_1250_apps
location: cspl_1250_apps/
volumes:
- name: volume_app_repo_us
storageType: s3
provider: aws
path: akondur-appframework-test/
endpoint: https://s3-us-west-2.amazonaws.com
region: us-west-2
secretRef: s3-secret
```
Error log:
```
2024-03-27T23:27:50.760455704Z  INFO    ValidateAppFrameworkSpec        Invalid value of maxConcurrentAppDownloads      {"controller": "standalone", "controllerGroup": "enterprise.splunk.com", …
```
> CSPL-2574 - Fix nil map error in appFramework validation

- go.mod
- go.sum
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/configuration.go
Customer is facing an [issue](https://github.com/splunk/splunk-operator/issues/1309) while installing an [app](https://splunkbase.splunk.com/app/3245) from Splunk base. Splunk Operator uses the following command to extract the app name:
```
tar tf <name> |head -1|cut -d/ -f1
```
In the case of harmless errors, we would want to log an error and continue with the installation. We will log errors with the Splunk Operator in all cases of errors/warnings but return error and fail installation only when the extracted name is empty
> CSPL-2598 - Fix app package name extraction logic

- Dockerfile
- pkg/splunk/enterprise/upgrade.go
Several customers have reported that the current upgrade flow of the Splunk Operator is causing delays in starting indexers and search head clusters due to the Monitoring Console (MC) container sometimes failing to start. The proposed new upgrade flow aims to speed up the process by altering the order in which components are started.
**Current Flow:**
- License Manager
- Cluster Manager
- MC
- Search Head
- Indexers
**Proposed New Flow:**
- License Manager
- Cluster Manager
- Search Head
- Indexers
> CSPL-2721: Upgrade Path : removed MC flow

- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/names.go
Adding access permissions to the telemetry app to address a vulnerability.
**Standalone**
```
[splunk@splunk-demo-standalone-0 metadata]$ pwd
/opt/splunk/etc/apps/app_tel_for_sok8s_stdaln/metadata
[splunk@splunk-demo-standalone-0 metadata]$ cat default.meta
[]
access = read : [ * ], write : [ admin ]
```
**LM**
```
[splunk@splunk-lm-example-c3-license-manager-0 metadata]$ pwd
/opt/splunk/etc/apps/app_tel_for_sok8s_lmanager/metadata
[splunk@splunk-lm-example-c3-license-manager-0 metadata]$ cat default.meta
[]
access = read : [ * ], write : [ admin ]
```
**SHC**:
```
[splunk@splunk-shc-example-c3-search-head-0 metadata]$ pwd
/opt/splunk/etc/apps/app_tel_for_sok8s_shc/metadata
[splunk@splunk-shc-example-c3-search-head-0 metadata]$ cat default.meta
[]
access = read : [ * ], write : [ admin ] …
```
> Add default.meta in the telemetry addressing vulnerability

- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
Addresses [PR#1372](https://github.com/splunk/splunk-operator/pull/1372)
> CSPL-2823 - Addresses PR#1372

- test/deploy-eks-cluster.sh
This PR introduces automation to clean up any remaining AWS resources, specifically **Security Groups** and **OIDC IDs**, after a Kubernetes cluster deletion. The objective is to ensure no orphaned resources are left behind once the pipeline completes, preventing unnecessary resource usage and avoiding potential security risks associated with leftover configurations.
- Implemented logic to delete **AWS Security Groups** associated with the cluster after deletion.
- Added cleanup for **OIDC ID** to remove any lingering identity provider configurations post-cluster deletion.
- Ensured the cleanup process runs at the end of the pipeline to capture any residual resources after all steps have completed.
Leaving behind AWS Security Groups and OIDC configurations can lead to:
- **Increased …
> Clean Up AWS Resources After Cluster Deletion

- kuttl/kuttl-test-helm-sva.yaml
- kuttl/tests/helm_sva/c3/00-assert.yaml
- kuttl/tests/helm_sva/c3/00-install-operator.yaml
- kuttl/tests/helm_sva/c3/01-assert.yaml
- kuttl/tests/helm_sva/c3/01-install-c3.yaml
- kuttl/tests/helm_sva/c3/02-assert.yaml
- kuttl/tests/helm_sva/c3/02-scaleup-c3.yaml
- kuttl/tests/helm_sva/c3/03-uninstall-c3.yaml
- kuttl/tests/helm_sva/c3/c3_config.yaml
- kuttl/tests/helm_sva/c3/c3_scale_config.yaml
- kuttl/tests/helm_sva/m4/00-install-operator.yaml
- kuttl/tests/helm_sva/m4/01-assert.yaml
- kuttl/tests/helm_sva/m4/01-install-m4.yaml
- kuttl/tests/helm_sva/m4/02-uninstall-m4.yaml
- kuttl/tests/helm_sva/m4/m4_config.yaml
- kuttl/tests/helm_sva/s1/00-install-operator.yaml
- kuttl/tests/helm_sva/s1/00-install-service-account.yaml
- kuttl/tests/helm_sva/s1/01-assert.yaml
- kuttl/tests/helm_sva/s1/01-install-standalone.yaml
- kuttl/tests/helm_sva/s1/02-assert.yaml
- kuttl/tests/helm_sva/s1/02-scaleup-standalone.yaml
- kuttl/tests/helm_sva/s1/03-assert.yaml
- kuttl/tests/helm_sva/s1/03-rollback-standalone.yaml
- kuttl/tests/helm_sva/s1/04-assert.yaml
- kuttl/tests/helm_sva/s1/04-monitoringconsole-standalone.yaml
- kuttl/tests/helm_sva/s1/05-assert.yaml
- kuttl/tests/helm_sva/s1/05-licensemanager-standalone.yaml
- kuttl/tests/helm_sva/s1/06-delete-standalone.yaml
- kuttl/tests/helm_sva/s1/06-errors.yaml
- kuttl/tests/helm_sva/script/installoperator.sh
Implement helm SVA testing only. The Helm tests currently test other features as well.
> CSPL-3063 -  Implement helm SVA testing only

- Dockerfile
Use sha instead of tag for docker build. This fixes https://github.com/splunk/splunk-operator/issues/1345.
> CSPL_3058 - Use sha instead of tag for docker build

- docs/OpenShift.md
Addressing openshift documentation [MR](https://github.com/splunk/splunk-operator/pull/1315/files).
> CSPL-3149 - Address openshift documentation

- pkg/splunk/enterprise/afwscheduler.go
GitHub Issue: https://github.com/splunk/splunk-operator/issues/1309
This issue was resolved in https://github.com/splunk/splunk-operator/pull/1327, but this error log makes it seem like app installation will still fail. Changing the log from error the info and updating the log should provide a better experience.
> [CSPL-3269] Change error log for clarification

- .github/workflows/automated-release-workflow.yml
- .github/workflows/merge-develop-to-main-workflow.yml
This change will make the distroless image build and push to dockerhub with the -distroless-RC tag in the splunk/splunk-operator-rc repository in the merge to main workflow, and the -distroless tag in the splunk/splunk-operator repository on the automated release workflow.
> Update distroless RC and release tags

- .github/workflows/automated-release-workflow.yml
- .github/workflows/build-test-push-workflow.yml
- .github/workflows/distroless-build-test-push-workflow.yml
This change moves pushing the latest dockerhub tag from the build-test-push workflow to the automated-release workflow. The latest tag and the release tag should be the same image, so pushing both together is the best option instead of pushing two separate images.
> Move pushing latest image from build test workflow to automated releasese workflow

- tools/bias_lang_migration.sh
This branch fixes bias_lang_migration.sh logic for handling monitoringConsole resource type
> CSPL-3435 Fix bias_lang_migration.sh logic for monitoringConsole

- .github/workflows/prodsec-workflow.yml
Ubuntu-20.04 is deprecated and will be unsupported in less than 1 month. [This page](https://github.com/actions/runner-images/issues/11101) suggests using ubuntu-latest as another option.
> Update semgrep scanner to run on ubuntu latest

- pkg/splunk/enterprise/configuration.go
This PR makes sure that if the CRD template default value of serviceTemplate/properties/spec/properties/type is overwritten to NodePort, then SOK doesn't try to overwrite it back to ClusterIP. ClusterIP is a Kubernetes default value for ServiceType, so no extra effort is required from SOK.
The following if condition is removed from the code. This way, SOK depends either on a Kubernetes default or on a user-provided default.
```
if spec.ServiceTemplate.Spec.Type == "" {
spec.ServiceTemplate.Spec.Type = corev1.ServiceTypeClusterIP
}
```
The change doesn't impact already existing tests. 
The change doesn't require any automated tests update or new tests because the CRD template is provided by the SOK team as it is defining a guideline on how to setup resources and modifications are possible, …
> CSPL-3518 Service Type default does not get overwritten if not set to ClusterIP

- test/deploy-eks-cluster.sh
This PR fixes string processing of the AWS policy for creating a cluster setup. Previously, running the policy related command in the terminal resulted in an incorrect output.
Changing `$variable` to `${variable}`.
Running the policy related command in a local setup resulted in a correct input. This is a helper script and doesn't require writing or updating automated tests.
**Github issue:** https://splunk.atlassian.net/browse/CSPL-3534
> CSPL-3534 Fixing string processing in cluster script

- .github/workflows/arm-AL2023-build-test-push-workflow-AL2023.yml
- .github/workflows/arm-AL2023-int-test-workflow.yml
- .github/workflows/arm-Ubuntu-build-test-push-workflow.yml
- .github/workflows/arm-Ubuntu-int-test-workflow.yml
This PR disables ARM AL2023 tests run for develop branch since these tests should only run for release of ARM version. Otherwise, they fail.
Removing `develop` branch name from a list of branches that are used to run ARM AL2023 tests.
No automated or manual tests are required. Once this PR gets merged to main, it will be validated automatically. 
**Github issue:** https://splunk.atlassian.net/browse/CSPL-3535
> CSPL-3529 Disable ARM Tests for Develop Branch

- docs/AppFramework.md
- pkg/splunk/enterprise/afwscheduler.go
- pkg/splunk/enterprise/afwscheduler_test.go
- pkg/splunk/enterprise/util.go
This pull request checks for an error returned from the getRemoteDataClientMgr() function to avoid a segmentation fault in an error case. A customer changed the name of an app source, and the status in the CR was not correctly updated, leading to this situation.
* `remoteDataClientMgr, _ := getRemoteDataClientMgr()` -> `remoteDataClientMgr, err := getRemoteDataClientMgr()`: Handle the situation where the operator is not able to get the remote data client manager due to the app source spec and status being out of sync. In this situation, we will gracefully log and error statement and continue with the reconciliation instead of seg faulting.
* Move `downloadWorker.waiter.Add(1)`: A waiter should only be incremented when we actually call a go routine. Moving this incrementation will make …
> CSPL-3499: Fix Segmentation Fault in Splunk Operator Due to App Volume Name Change

- test/appframework_aws/c3/manager_appframework_test.go
- test/appframework_aws/s1/appframework_aws_test.go
This pull request introduces wait times after updating a CR in a test case and before checking the status. In the internal GitLab pipelines, these two test cases fail much more often than others. This is due to the fact that the "Ready" state of the CR from before the update is found before the update is applied, and the test case thinks that the "Ready" turns to an "Error". In reality, waiting even .5 seconds before checking the state will allow the CR to update and wait for the new "Ready" state to take effect and be consistent. I added a 1 second wait to be sure.
This is possibly related to similar fixes being done on the event emitting for test cases, but this small PR will be a quick fix for these specific tests.
test/appframework_aws/c3/manager_appframework_test.go and …
> Add wait in test cases after updating CR and before checking status

- helm-chart/splunk-operator/templates/deployment.yaml
- helm-chart/splunk-operator/values.yaml
Linked issue #1478 
This PR introduces `extraEnvs` list to `splunk-operator`'s values.yaml. This field is used by `deployment.yaml` template to inject custom envs provided by users.
> bugfix: add extraEnvs to splunk-operator helm-chart

- .github/workflows/int-test-gcp-workflow.yml
- .github/workflows/int-test-workflow.yml
- pkg/splunk/enterprise/clustermanager.go
- pkg/splunk/enterprise/clustermaster.go
- pkg/splunk/enterprise/indexercluster.go
- pkg/splunk/enterprise/licensemanager.go
- pkg/splunk/enterprise/licensemaster.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/standalone.go
- pkg/splunk/enterprise/util.go
- pkg/splunk/enterprise/util_test.go
This PR fixes a bug where a Smart Store secret created manually gets removed by the operator on Splunk resources removal because owner references are set by the Operator on the Splunk resources creation for given secret while it should not be managed by SOK.
Moving the DeleteOwnerReferencesForS3SecretObjects execution outside of DeleteOwnerReferencesForResources execution and outside of if cr.ObjectMeta.DeletionTimestamp != nil condition. Additionally, a small check needed to be added to the condition to make unit tests running since they rely on a namespaced secret, not a separate Smart Store secret.
Tested manually for S1, C3, M4, S1 & LM & MC, C3 & LM & MC and M4 & LM & MC. Automated tests executed as a part of the process.
https://splunk.atlassian.net/browse/CSPL-3704 …
> CSPL-3704 #1474 Secret Management: SOK deletes automatically smartstore secrets created

- helm-chart/splunk-enterprise/values.yaml
This pull request sets a default value for the imagePullPolicy in the splunk/splunk-enterprise helm chart. The CRs require the imagePullPolicy to be "Always" or "IfNotPresent", so setting this default removes unnecessary errors without requiring the user to update the value. "IfNotPresent" is used as default in other places in the code.
- helm-chart/splunk-enterprise/values.yaml: Set default value for `image.imagePullPolicy`
- Tested by installing a c3 instance on an AWS EKS cluster.
- Before the changes, kubectl events show `Could not update annotations. Reason ClusterManager.enterprise.splunk.com "cm" is invalid: spec.imagePullPolicy: Unsupported value: "": supported values: "Always", "IfNotPresent"`
- After the changes, these events are now shown.
- …
> CSPL-3706: Default imagePullPolicy in Helm Chart 

- .github/workflows/int-test-workflow.yml
- Dockerfile
- Makefile
This PR updates the manifest for the latest ubi8-minimal image to use as the base image in the Makefile and Dockerfile. This new version includes vulnerability fixes for included packages.
* Dockerfile: Update the BASE_IMAGE_VERSION to use to build the image
* Makefile: Update the BASE_IMAGE_VERSION to use to build the image
All unit, smoke, and integration tests were run.
- https://splunk.atlassian.net/browse/CSPL-3784
- https://splunk.atlassian.net/browse/VULN-35964
- https://splunk.atlassian.net/browse/VULN-35965
- https://splunk.atlassian.net/browse/VULN-35966
> CSPL-3784: Update base image to latest ubi8-minimal version

- .github/workflows/int-test-workflow.yml
- go.mod
- go.sum
- internal/controller/common/predicate.go
This pull request updates the dependency version of golang.org/x/net dependencies to mitigate medium severity security vulnerabilities.
golang.org/x/net
- https://pkg.go.dev/vuln/GO-2025-3595
- Severity: SEC_MEDIUM
- The tokenizer incorrectly interprets tags with unquoted attribute values that end with a solidus character Check Mark as self-closing. When directly using Tokenizer, this can result in such tags incorrectly being marked as self-closing, and when using the Parse functions, this can result in content following such tags as being placed in the wrong scope during DOM construction, but only when tags are in foreign content (e.g. <math>, <svg>, etc contexts).
go.mod and go.sum:
- Update versions of dependencies.
Unit tests, smoke tests, and integration tests all run and are …
> Upgrade golang.org/x/net version to v0.38.0

- docs/AppFramework.md
This pull request updates the `docs/AppFramework.md` file to clarify how the App Framework handles app updates, particularly focusing on checksum (Etag) usage and troubleshooting guidance. The key changes include detailed explanations of checksum behavior, restrictions on archive file naming, and new troubleshooting sections.
- docs/AppFramework.md: Explain app update logic, add troubleshooting for apps not being updated, add troubleshooting for apps not being installed.
N/A
- https://splunk.atlassian.net/browse/CSPL-3783
- https://splunk.atlassian.net/browse/CSPL-3798
> CSPL-3783: Update AppFramework docs with troubleshooting information

- pkg/splunk/enterprise/afwscheduler.go
As a response to a few community group discussions, this PR adds more logging around the app framework download work logic.
- Add error log for unable to create download directory.
- Update error log with more information for invalid statuses and phases.
N/A
- https://splunk.atlassian.net/browse/CSPL-3798
> CSPL-3798: Add more logs around invalid phase and downloadPending

- docs/Ingress.md
- test/deploy-eks-cluster.sh
- This PR enhances the Ingress documentation to include session stickiness configuration for proper work of Splunk.
- This PR fixes variable references in one of the scripts.
- Session stickiness added to Ingress documentation.
- Variable references changed from `$var` to `${var}`.
N/A
Jira item: https://splunk.atlassian.net/browse/CSPL-3851
> CSPL-3851 Session Stickiness for Ingress 

- .github/workflows/build-test-push-workflow.yml
- api/v4/clustermanager_types.go
- pkg/splunk/enterprise/searchheadcluster.go
- pkg/splunk/enterprise/searchheadcluster_test.go
- pkg/splunk/enterprise/util.go
This PR fixes the handling of error scenarios for search head cluster and cluster manager CRs. SearchHeadCluster CRs were not showing error messages due to an invalid `DeployerPhase` value. ClusterManager CRs were not showing events due to an incorrect `Kind` value. Logs and unit tests were added to verify this issue is fixed and help debug in the future.
* Corrected the `Kind` field value in `ClusterManager` events from `"Clustermanager"` to `"ClusterManager"` to ensure proper object references. (`api/v4/clustermanager_types.go`)
* Added a new `DeployerPhase` field initial value of `PhaseError` during the cluster's initialization. This is required for shc with validation errors to be retrieved by the operator. (`pkg/splunk/enterprise/searchheadcluster.go`)
* Unit test added
* Deployed a …
> CSPL-3867: SHC and CM Error Message Visibility

- helm-chart/splunk-operator/templates/app_download.yaml
- helm-chart/splunk-operator/templates/service.yaml
- helm-chart/splunk-operator/templates/serviceaccount.yaml
This PR allows users to set labels on the splunk operator controller manager service account and service created by helm deployments. Previously, these two entities would only use default labels created by the helm chart, but it will now include any labels added by the user through the `splunkOperator.labels` field, similar to how the deployment is already created.
- Update helm chart templates to copy labels to service and service account for splunk operator
Manual testing before and after changes using the following values.yaml file:
```
splunkOperator:
labels:
custom-label: raizel
persistentVolumeClaim:
storageClassName: "gp2"
splunkGeneralTerms: "--accept-sgt-current-at-splunk-com"
```
- 3.0.0 release: `helm install splunk-operator splunk/splunk-operator -f values.yaml`
```
% kubectl …
```
> CSPL-4027: Allow custom labels on helm chart service and service account
