build/Dockerfile

Corresponding openshift project:
https://connect.redhat.com/project/1896861/certification/sha256%3A87eb3210f1797dab4388576b2be4762f9a7228188b6256a916194dcb530fcc26

Openshift comply

---

pkg/splunk/enterprise/configuration.go

Expose port 8088 on indexers for HEC
Also, only expose ports for DFC (DFS component) on search heads

Expose port 8088 on indexers for HEC

---

.circleci/config.yml
Makefile
README.md
build/Dockerfile.builder
deploy/all-in-one-cluster.yaml
deploy/all-in-one-scoped.yaml
deploy/rbac.yaml
go.mod
go.sum

Sample CircleCI config to execute something. The format should be correct, I'm not actually sure if this works because I can't configure anything on CircleCI because it says I don't have any access to the splunk-operator project on CircleCI (maybe I'm not an admin there?)
But yeah, very possible we need to do something on CircleCI to get this working.

Adding initial circleci configs

---

docs/StorageClass.md

Added example for configuring StorageClass

---

docs/StorageClass.md

and pointers for using Local Persistent Volumes.

Updated storage docs to include new ephemeralStorage feature

---

pkg/splunk/common/util.go
pkg/splunk/common/util_test.go
pkg/splunk/enterprise/standalone.go
pkg/splunk/enterprise/standalone_test.go

Also fixed bug with labels and annotations set by operator being clobbered by labels and annotations set on custom resources.

Added regular service for Standalone custom resource

---

test/smoke/smoke_test.go
test/testenv/deployment.go

- Added new test case for Multisite Indexer Cluster 
- Modified existing Single site test case to use separate config for CM.
- Added new methods for Multisite Indexer Cluster 
- Added new method for single site Indexer Cluster

CSPL-274: Update multisite test cases

---

.circleci/config.yml
test/monitoring_console/monitoring_console_suite_test.go
test/monitoring_console/monitoring_console_test.go
test/run-tests.sh
test/smoke/cluster_master_sites_response.go
test/smoke/smoke_test.go
test/testenv/mcutil.go
test/testenv/testenv.go
test/testenv/util.go
test/testenv/verificationutils.go

Test Cases Added:
- MC is configured with 2 different standalone deployments
- MC is configured with standalone when scaled up
- MC is configured with SHC and Standalone in same namespace
- MC is configured with SHC when its scaled up

CSPL-382: Test for monitoring console changes

---

docs/CONTRIBUTING.md
docs/CustomResources.md
docs/Examples.md
docs/Install.md
docs/MultisiteExamples.md
docs/README.md

Added some minor changes to docs regarding Multisite indexer cluster and Cluster Master.

Minor changes to docs

---

pkg/splunk/enterprise/monitoringconsole.go
test/smoke/smoke_test.go

-BugFix
- Setting owner reference for the stateful set after creating of sts

MC Statefulset Owner

---

pkg/splunk/enterprise/configuration.go

- when creating MC with license master it was adding license volume mount on MC

CSPL-511 - Avoid adding volume mounts for MC

---

LICENSE
deploy/olm-catalog/splunk/0.2.0/splunk.v0.2.0.clusterserviceversion.yaml
deploy/operator.yaml
docs/README.md

Added a copyright license file.

CSPL-512: Added a copyright license and update readme.md for reading global secrets object

---

LICENSE
deploy/olm-catalog/splunk/0.2.0/splunk.v0.2.0.clusterserviceversion.yaml
deploy/operator.yaml
docs/Examples.md
docs/MultisiteExamples.md
docs/README.md
docs/SmartStore.md
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/finalizers_test.go
pkg/splunk/enterprise/indexercluster.go

Merge develop into master for 0.2.0 beta release

Merge develop into master for 0.2.0 beta release 

---

docs/Install.md
docs/README.md

Convert tiny cc urls to long urls

Convert tiny cc urls to long urls

---

docs/README.md

CSPL-562: Update README.md

---

pkg/splunk/enterprise/indexercluster.go
pkg/splunk/enterprise/indexercluster_test.go
pkg/splunk/enterprise/util_test.go
pkg/splunk/spark/spark_test.go
pkg/splunk/test/controller.go

This PR focusses on increasing code coverage for indexercluster.go. There will be another PR which focuses on increasing code coverage for clustermaster.go

CSPL-556(Part-1): This change is first part of increasing the code coverage for clustering code. This PR focuses on indexercluster.go

---

pkg/splunk/common/messages.go
pkg/splunk/common/names.go
pkg/splunk/enterprise/indexercluster.go
pkg/splunk/enterprise/indexercluster_test.go
pkg/splunk/enterprise/names.go
pkg/splunk/enterprise/searchheadcluster.go
pkg/splunk/enterprise/searchheadcluster_test.go
pkg/splunk/util/messages.go
pkg/splunk/util/secrets.go
pkg/splunk/util/secrets_test.go

Changes to improve code coverage for password management. Added coverage to secret utils, ApplyIdxcSecret and ApplyShcSecret.

Code coverage for password management

---

docs/README.md

Fix reading the global k8s secret object link

Fix read global object link

---

.circleci/config.yml

https://circleci.com/developer/orbs

Bring orbs current in CircleCI

---

docs/ChangeLog.md

Add release date to 0.2.1 beta in docs/ChangeLog.md

add date to 0.2.1 Beta in changelog

---

.circleci/config.yml
test/delete_cr/deletecr_test.go
test/example/example_suite_test.go
test/ingest_search/ingest_search_test.go
test/monitoring_console/monitoring_console_test.go
test/run-tests.sh
test/smoke/smoke_test.go
test/testenv/mcutil.go

* Added keyword to test cases so that they can be filtered by ginkgo
* Added a nightly build workflow to cirlce CI config
* Change integration test to smoke test to represent the running test cases
* Modified test selection logic in run_test.sh

Added option to pass test selection env variable through CIRCLE CI

---

test/smoke/smoke_test.go

PR Uses existing functions to assert that LM is configured on MC pod

CSPL-547: Test Automation to Verify MC configured with LM

---

docs/README.md

Adding a link to the security page in the Readme.md. 
No other changes in content were made.

Added link to Security Page

---

.circleci/config.yml
test/licensemaster/lm_test.go
test/monitoring_console/monitoring_console_test.go
test/testenv/deployment.go
test/testenv/mcutil.go
test/testenv/testenv.go
test/testenv/verificationutils.go

Refactored Monitoring Console Test Automation: 
- Combined two SHC test for faster run times and less resource usage.
- Refactored MC Util code
- Refactored LM code to use existing string formatted variable
-  Added verification for Indexers on MC 
- Added a test to scale Indexer Cluster and make sure new indexer shows up on MC

CSPL-898-fix-mc-test

---

pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/monitoringconsole.go

-Use predefined resource values for MC pod
-Don't use cr defined resource values for MC

CSPL-555 Use predefined resource values for MC pod

---

deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_clustermasters_crd.yaml
deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_licensemasters_crd.yaml
deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.0/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.0/splunk.v1.0.0.clusterserviceversion.yaml
docs/ChangeLog.md
docs/Install.md
docs/README.md
docs/SplunkOperatorUpgrade.md
version/version.go

Helper develop commit for 1.0.0. GA release

Helper develop commit for 1.0.0. GA release

---

.circleci/config.yml

Update NUM_NODES and NUM_WORKERS to increase parallel execution of test cases on EKS Cluster.

Update nodes of cluster and parallel test for faster execution on EKS

---

test/custom_resource_crud/custom_resource_crud_c3_test.go
test/custom_resource_crud/custom_resource_crud_m4_test.go
test/delete_cr/deletecr_test.go
test/licensemaster/lm_c3_test.go
test/licensemaster/lm_m4_test.go
test/licensemaster/lm_s1_test.go
test/monitoring_console/monitoring_console_test.go
test/scaling_test/scaling_test.go
test/secret/secret_c3_test.go
test/secret/secret_m4_test.go
test/secret/secret_s1_test.go
test/smartstore/smartstore_test.go
test/smoke/smoke_test.go

Updated the test cases to disable MC verifications and MC test case.

CSPL-1052-disabled MC verifications and test

---

pkg/splunk/enterprise/clustermaster.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/licensemaster.go
pkg/splunk/enterprise/licensemaster_test.go
pkg/splunk/enterprise/monitoringconsole_test.go
pkg/splunk/enterprise/searchheadcluster.go
pkg/splunk/enterprise/searchheadcluster_test.go
pkg/splunk/enterprise/standalone.go
pkg/splunk/enterprise/standalone_test.go
pkg/splunk/enterprise/util.go
pkg/splunk/enterprise/util_test.go

- Addressed some fixes around the integration tests
- Added some UT modifications, and also some code restructuring

CSPL-1080: Test and fix issues after integrating CSPL-1004 & CSPL-765

---

deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_clustermasters_crd.yaml
deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_licensemasters_crd.yaml
deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.1/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.1/splunk.v1.0.1.clusterserviceversion.yaml
deploy/operator.yaml
docs/ChangeLog.md
docs/Images.md
docs/Install.md
docs/README.md
docs/SplunkOperatorUpgrade.md
version/version.go

Splunk Operator 1.0.1GA release

Splunk Operator 1.0.1 release

---

test/testenv/appframework_utils.go
test/testenv/s3utils.go
test/testenv/verificationutils.go

Added Test case utils details below:
* Utility function to get the install status and app version for an app
* Verification util to iterate and check multiple apps
* Verification to validate apps are copied/downloaded to location

CSPL-1081: Automation for app framework phase 2

---

test/c3/appframework/appframework_suite_test.go
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_suite_test.go
test/m4/appframework/appframework_test.go
test/smartstore/smartstore_test.go
test/testenv/deployment.go
test/testenv/remote_index_utils.go
test/testenv/s3utils.go
test/testenv/testenv.go
test/testenv/util.go
test/testenv/verificationutils.go

Added Test Cases to verify init-container download apps on S1, C3, M4 SVA
**Added/Modified S3 utils:** 
- Return file name under a directory
- Delete file on S3
- Download Multiple files from S3
- Upload Multiple files from S3
- Added missing logic to UploadFileToS3
**Other Changes**
-  Resolved existing S1 test case failure due to missing keys in Volume Spec 
-  Added util to get files under a given directory
-  Added verification utils to validate apps downloaded by init-container
- Resolved issue with (CM, SH) Spec methods not using LM ref and defaults string but accepting them as parameters
**Test Results**
```
• [SLOW TEST:533.356 seconds]
c3appfw test
/Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/c3/appframework/appframework_test.go:27
Single Site Indexer …
```

CSPL-1069-added-automation for init container

---

.circleci/config.yml

* Added app framework feature branch to nightly build
* Added appframework test to nightly run

Added appframework feature branch to nightly run

---

.circleci/config.yml

Created a new workflow for feature branch only. 
Its scheduled to run at 11 AM.

Added new circle config for nightly run on feature branch

---

.circleci/config.yml

Introduced new workflow to run test on app framework feature branch
Commit to feature branch -> Run App Framework Test    ---- (Success)----->   Run Integration Test

Introduce new pipeline to run app framework test

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go

Automation for M4, C3, S1 deployment to verify apps are copied to newly created Standalone, Indexer, SH with Scale Up.
```
[2]
[2] • [SLOW TEST:2112.555 seconds]
[2] m4appfw test
[2] /Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/m4/appframework/appframework_test.go:29
[2]   Multi Site Indexer Cluster with SHC (m4) with App Framework
[2]   /Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/m4/appframework/appframework_test.go:63
[2]     integration, m4, appframework: can deploy a M4 SVA with App Framework enabled
[2]     /Users/pdhanoya/splunk-operator-git/automation/splunk-operator/test/m4/appframework/appframework_test.go:64
[2] ------------------------------
[2] {"level":"info","ts":1626134678.544024,"msg":"testenv …
```

Cspl 1145- Automation to verify apps are copied to new pods on scale up

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go

Recreated PR for https://github.com/splunk/splunk-operator/pull/412 with correct target branch

CSPL-1145: automation for app framework with scale up

---

.circleci/config.yml

Reverted app framework nightly changes on develop branch

CSPL-1155-revert-develop-pipeline-changes

---

pkg/apis/enterprise/v2/common_types.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/names.go
pkg/splunk/enterprise/util.go
pkg/splunk/enterprise/util_test.go

- fixing some todo comments for phase-3

---

deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
deploy/crds/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/crds/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_clustermasters_crd.yaml
deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_licensemasters_crd.yaml
deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.2/enterprise.splunk.com_standalones_crd.yaml

restoring the missing protocol field from CRDs.

- restoring the missing protocol field from CRDs.

---

.circleci/config.yml
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go

Split app fw test into int, smoke. Remove feature branch workflow

Split app fw test into int, smoke. Remove feature branch workflow

---

.circleci/config.yml

Added app framework feature branch to nightly run

Added feature branch to nightly run

---

.circleci/config.yml
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/testenv/deployment.go

Int test changes to disable failing validations and increase probe time.

Int test changes

---

deploy/olm-catalog/splunk/1.0.2/splunk.v1.0.2.clusterserviceversion.yaml
docs/ChangeLog.md

Updating the change log with the release 1.0.2 info

- Updating the change log with the release 1.0.2 info

---

.circleci/config.yml
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go

Created a new pipeline for app framework test cases.

Split nightly int test into app framework and int test pipeline

---

test/c3/appframework/appframework_test.go

This C3 test will deploy IDXC and SHC, setup app framework spec on CM and Deployer with 2 buckets, 1 for local install, 1 for cluster wide install, and check everything is installed at the correct location.
Test run:
[2] • [SLOW TEST:621.502 seconds]
[2] c3appfw test
[2] /Users/jambrosiano/splunk-operator/CSPL1216/splunk-operator/test/c3/appframework/appframework_test.go:29
[2]   Clustered deployment (C3 - clustered indexer, search head cluster)
[2]   /Users/jambrosiano/splunk-operator/CSPL1216/splunk-operator/test/c3/appframework/appframework_test.go:428
[2]     c3, integration, appframework: can deploy a C3 SVA with apps installed locally on CM and SHC Deployer, and cluster-wide on Peers and SHs
[2]     /Users/jambrosiano/splunk-operator/CSPL1216/splunk-operator/test/c3/appframework/appf …

CSPL-1216: App framework automation: Adding test to install locally and cluster-wide simultaneously

---

pkg/splunk/enterprise/clustermaster.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/indexercluster.go
pkg/splunk/enterprise/monitoringconsole_test.go

[CSPL-1089] Update MC for idxc

---

test/s1/appframework/appframework_test.go

Removed installation of normal apps along with ES apps.

Fixed ES app test

---

.github/workflows/int-test-workflow.yml
.github/workflows/nightly-int-test-workflow.yml

Renamed step name in int and nightly workflows to represent correct name.

Update the name of int test step

---

.github/workflows/pre-release-workflow.yml

Update the URL update rule in pre release workflow based on [this](https://github.com/splunk/splunk-operator/pull/511/files#r708751400) comment

Update the URL on release github action rule

---

pkg/splunk/enterprise/indexercluster.go

Wrong err condition check and not returning mcRef retrieved from CM Spec

CSPL-1362: MC not getting updated on scaling Indexers

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_suite_test.go
test/s1/appframework/appframework_test.go
test/testenv/appframework_utils.go
test/testenv/util.go
test/testenv/verificationutils.go

Alternate PR for https://github.com/splunk/splunk-operator/pull/551

CSPL-1345-test changes for app framework phase 3 download api

---

.github/workflows/automated-release-workflow.yml
.github/workflows/pre-release-workflow.yml

* Updated regex for string match to update operator version
* Made improvement in include exclude logic

CSPL-1447-updated-regex-to-update-operator-version

---

test/s1/appframework/appframework_test.go

Backport for PR https://github.com/splunk/splunk-operator/pull/582.

CSPL-1454: Fix s1 appframework test (#582)

---

deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
deploy/crds/enterprise.splunk.com_monitoringconsoles_crd.yaml
deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/crds/enterprise.splunk.com_standalones_crd.yaml
pkg/apis/enterprise/v3/common_types.go
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/licensemaster.go
pkg/splunk/enterprise/monitoringconsole.go
pkg/splunk/enterprise/standalone.go
pkg/splunk/enterprise/types.go
pkg/splunk/enterprise/util.go
pkg/splunk/enterprise/util_test.go

Added playbook for local scoped app installation
UT:
appSrcDeployStatus:
splunkFwdApps:
appDeploymentInfo:
- appName: Splunk_TA_aws-5.0.2.spl
auxPhaseInfo:
- phase: install
status: 303
- phase: install
status: 303
deployStatus: 3
isUpdate: false
objectHash: '"b38a8f911e2b43982b71a979fe1d3c3f"'
phaseInfo:
phase: install
status: 303
repoState: 1
- appName: Splunk_TA_paloalto-3.6.1-3610.tgz
auxPhaseInfo:
- phase: install
status: 303
- phase: install
status: 303
deployStatus: 3
isUpdate: false
objectHash: '"3d864310fdea6254446f3d1adfd78515"'
phaseInfo:
phase: install
status: 303
repoState: 1
appsRepoStatusPollIntervalSeconds: 600
```
[splunk@splunk-s2apps-standalone-1 splunk]$ ls -l /opt/splunk/etc/apps/
total 112
drwxr-sr-x  4 splunk splunk 4096 Jun  8 09:27 SplunkForwarder
drwxr-sr-x  4 …
```

CSPL-1331: API for local scoped app pkg install

---

test/c3/appframework/appframework_test.go
test/deploy-eks-cluster.sh
test/testenv/deployment.go

Backport of CSPL-1458 into feature-appframework branch

CSPL-1477: Backport of CSPL-1458: Fixing failing C3 appframework test into feature-appframework branch

---

test/m4/appframework/appframework_test.go

Changing upload logic for M4 downgrade test

[CSPL-1497] Fix M4 int test failure

---

deploy/crds/enterprise.splunk.com_clustermasters_crd.yaml
deploy/crds/enterprise.splunk.com_licensemasters_crd.yaml
deploy/crds/enterprise.splunk.com_monitoringconsoles_crd.yaml
deploy/crds/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/crds/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.3/splunk.v1.0.3.clusterserviceversion.yaml
pkg/apis/enterprise/v3/common_types.go
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/enterprise/clustermaster.go
pkg/splunk/enterprise/names.go
pkg/splunk/enterprise/types.go
pkg/splunk/enterprise/util.go
pkg/splunk/enterprise/util_test.go
pkg/splunk/util/util.go
pkg/splunk/util/util_test.go

This PR targets the following things - 
1. Implement a runbook for cluster scoped apps for indexer cluster
2. Runbook will trigger a bundle push and will check the status of bundle push in each reconcile.

CSPL-1332: Cluster scoped playbook impementation for indexer cluster

---

README.md
build/Dockerfile.builder

Updated docs with go version 1.17.3

Cspl 1455: Updated docs with go Version

---

test/s1/appframework/appframework_test.go

CSPL-1511: Backport CSPL-1418 (Use common utility to create appframework spec for S1)

---

test/m4/appframework/appframework_test.go
test/testenv/deployment.go

Backport of CSPL-1419 to feature-appframework branch

CSPL-1512: Backport of CSPL-1419 (use different App Source for every CR for M4 test cases)

---

test/c3/appframework/appframework_suite_test.go
test/c3/appframework/appframework_test.go
test/licensemanager/lm_c3_test.go
test/m4/appframework/appframework_suite_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_suite_test.go
test/s1/appframework/appframework_test.go
test/testenv/appframework_utils.go

Migrate Phase 3 app structure to develop

CSPL-1542:Migrate Phase 3 app structure to develop

---

test/c3/appframework/appframework_suite_test.go
test/c3/appframework/appframework_test.go
test/licensemanager/lm_c3_test.go
test/m4/appframework/appframework_suite_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_suite_test.go
test/s1/appframework/appframework_test.go
test/testenv/appframework_utils.go
test/testenv/deployment.go
test/testenv/verificationutils.go

* Added phase 3 for S1, C3 and M4 SVA.
* Refactored GetAppFileList function to be inline with Phase3
* Refactored Deploy functions for C3 and M4 to return CR objects

CSPL-1469-added phase 3 for S1, C3 and M4 SVA.

---

pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/enterprise/names.go
pkg/splunk/enterprise/searchheadcluster.go
pkg/splunk/enterprise/types.go
pkg/splunk/enterprise/util.go
pkg/splunk/util/util.go

This PR targets the following things - 
1. Implement a playbook for installing apps for SHC
2. Fix bug/s found as part of CSPL-1515 while downloading apps.

CSPL-1333: Implement playbook for SHC

---

test/testenv/verificationutils.go

(cherry picked from commit 2f942e4f02c4cef4fd9275cecef966ca4cff2d5a)
Original PR: https://github.com/splunk/splunk-operator/pull/616/files

Workaround for CSPL-1532 (#616)

---

pkg/apis/enterprise/v3/common_types.go
pkg/splunk/client/s3client.go
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/enterprise/clustermaster.go
pkg/splunk/enterprise/licensemaster.go
pkg/splunk/enterprise/monitoringconsole.go
pkg/splunk/enterprise/searchheadcluster.go
pkg/splunk/enterprise/standalone.go
pkg/splunk/enterprise/types.go
pkg/splunk/enterprise/util.go
pkg/splunk/enterprise/util_test.go

Support for install worker handler

CSPL-1449: Support for install worker handler

---

deploy/olm-catalog/splunk/1.0.4/enterprise.splunk.com_clustermasters_crd.yaml
deploy/olm-catalog/splunk/1.0.4/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.4/enterprise.splunk.com_licensemasters_crd.yaml
deploy/olm-catalog/splunk/1.0.4/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.4/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.4/splunk.v1.0.4.clusterserviceversion.yaml
deploy/operator.yaml
docs/ChangeLog.md
docs/Images.md
docs/Install.md
docs/README.md
docs/SplunkOperatorUpgrade.md
version/version.go

Merge master into develop.
- SOK release 1.0.4 was done from the master branch. So, merging the master to develop

CSPL-1551: Merge master into develop

---

deploy/cluster_role.yaml
deploy/olm-catalog/splunk/1.0.5/enterprise.splunk.com_clustermasters_crd.yaml
deploy/olm-catalog/splunk/1.0.5/enterprise.splunk.com_indexerclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.5/enterprise.splunk.com_licensemasters_crd.yaml
deploy/olm-catalog/splunk/1.0.5/enterprise.splunk.com_searchheadclusters_crd.yaml
deploy/olm-catalog/splunk/1.0.5/enterprise.splunk.com_standalones_crd.yaml
deploy/olm-catalog/splunk/1.0.5/splunk.v1.0.5.clusterserviceversion.yaml
deploy/operator.yaml
docs/ChangeLog.md
docs/Images.md
docs/Install.md
docs/README.md
docs/SplunkOperatorUpgrade.md
version/version.go

CSPL-1555: SOK Release 1.0.5

---

test/c3/appframework/appframework_test.go

Updated C3 case with  both local and cluster with changes:
- Local & Cluster apps should have different App source location
- Add additional Phase3 specific verifications for each CR need to be added as follows:
1. Verify Apps Downloaded in App Deployment Info
2. Verify Apps Copied in App Deployment Info
3. Verify App Package is deleted from Operator Pod
4. Verify Apps Installed in App Deployment Info
5. Verify App Package is deleted from Splunk Pod
6. Verify App Directory in under splunk path
7. Verify App enabled  and version by running splunk cmd

CSPL:1527 C3 test cases with both local and cluster install

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go

Added MC spec to test cases with manual poll.
```
Results:
• [SLOW TEST:468.025 seconds]
s1appfw test
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:32
Standalone deployment (S1) with App Framework
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:1031
s1, smoke, appframework: can deploy a standalone instance with App Framework enabled for manual poll
/Users/tpereira/Git/splunk-operator/test/s1/appframework/appframework_test.go:1032
{"level":"info","ts":1641337241.67758,"msg":"testenv deleted.\n","testenv":"s1appfw-szm"}
JUnit report was created: /Users/tpereira/Git/splunk-operator/test/s1/appframework/s1appfw-szm_junit.xml
Ran 1 of 6 Specs in 509.090 seconds
SUCCESS! -- 1 Passed | 0 Failed | 5 …
```

CSPL-1496: Added MC scenario existing to manual poll cases

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/testenv/appframework_utils.go

Changes:
- Added  test cases in c3 and m4 for manual polling with local scope install
- Fixed a small error in app-framework utils code
```
Test Results:
• [SLOW TEST:561.669 seconds]
c3appfw test
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:31
Clustered deployment (C3 - clustered indexer, search head cluster)
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:2620
smoke, c3, appframework: can deploy a C3 SVA and have apps installed abd updated locally on Cluster Manager and Deployer for manual polling
/Users/tpereira/Git/splunk-operator/test/c3/appframework/appframework_test.go:2621
CSPL: Test cases for c3 and m4 appframework with local scope and manual polling …
```

CSPL-1538: Test cases for c3 and m4 appframework with local scope and manual polling

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go
test/testenv/appframework_utils.go

Added a util function to check for phase changes to detect upgrade/downgrade poll trigger.

CSPL-1566:  Add phase change logic to replace aggressive wait

---

pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go

For cluster scoped apps, once the podCopy is complete, on reconcile re-entry do not create a worker in the scheduler pipeline

CSPL-1591: Cluster scope: avoid unnecessary scheduling of the podcopy workers

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
.github/workflows/nightly-int-test-workflow.yml
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go

Original PR https://github.com/splunk/splunk-operator/pull/675/files. 
Backport splitting of Appframework Test to Develop.

Backport for PR 675

---

test/s1/appframework/appframework_test.go

S1 automation test covering the following case:
- Create and apply 2 Standalone deployments – installation should be in parallel for both
- Install & verify common set of Apps for both, and unique set of apps for each
- Verify all apps correctly installed eventually

CSPL-1597: Multiple standalone in same namespace

---

.env
.github/workflows/automated-release-workflow.yml
.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
.github/workflows/merge-develop-to-master-workflow.yml
.github/workflows/nightly-int-test-workflow.yml
.github/workflows/pre-release-workflow.yml
pkg/splunk/client/minioclient.go
pkg/splunk/controller/configmap.go
pkg/splunk/controller/statefulset.go
pkg/splunk/enterprise/monitoringconsole_test.go
test/testenv/verificationutils.go

Merge `develop` into `feature-appframework`

CSPL-1656: Merge branch 'develop' into feature-appframework

---

config/examples/advanced/README.md
config/examples/advanced/c1.yaml
config/examples/advanced/c3.yaml
config/examples/advanced/hwf.yaml
config/examples/advanced/s1.yaml
docs/Examples.md

Update documentation on develop to accommodate the following:
Commit https://github.com/splunk/splunk-operator/commit/319978158291637824767bd5699e071d5f964d6a
Commit https://github.com/splunk/splunk-operator/commit/6fabaf08ef36235ba956a5206bc6fef356fa07ba
Commit https://github.com/splunk/splunk-operator/commit/39ff709e0fd69d1b45e962949323af81696614b8
Commit https://github.com/splunk/splunk-operator/commit/a32c15bfaab8d97484875e1ebfa32eb783932436
Commit https://github.com/splunk/splunk-operator/commit/3d4a9d86d3edb1bdd874ebab53890cce5ba4c3f0
PR https://github.com/splunk/splunk-operator/pull/676

CSPL-1651: Update documentation

---

docs/SplunkOperatorUpgrade.md

minor change to argument list in upgrade-to-1.1.0.sh script

adding small change to documenation

---

.github/workflows/automated-release-workflow.yml
.github/workflows/pre-release-workflow.yml
Makefile

changed release workflow to use latest 1.1.0 changes
1. changed makefile
2. changed workflow to use `make` command for creating artifacts and docker images

CSPL-1678: Sdk release changes

---

test/deploy-eks-cluster.sh
test/run-tests.sh

Backport  for PR https://github.com/splunk/splunk-operator/pull/715/files.

CSPL-1664 improve cluster down command (#715)

---

docs/SplunkOperatorUpgrade.md
tools/cleanup.sh

version added from 8.2.3 to 8.2.6 
cleanup script changed to address `pvc` deletion

documentation and script changes for upgrade scenario 

---

test/c3/appframework/appframework_suite_test.go
test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_suite_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_suite_test.go
test/s1/appframework/appframework_test.go
test/testenv/appframework_utils.go
test/testenv/verificationutils.go

S1, C3, M4 automation test covering the following case:
- Create and apply CR spec with app source containing several apps.
- Wait for installation to be done.
- Check value of repoStatein CR is equal to 1 (RepoStateActive )
- Manually disable 1 app (update app package with 'state = disabled' in app.conf for that app)
- wait for disabled app update to complete on splunk pod
- Remove the app from app source
- Check value of repoStatein CR is equal to 2 (RepoStateDeleted )
Int test pass link: https://github.com/splunk/splunk-operator/runs/5983885428?check_suite_focus=true

CSPL-1599: Test cases to verify feature disable

---

.github/workflows/automated-release-workflow.yml
docs/ChangeLog.md
docs/SplunkOperatorUpgrade.md
tools/upgrade-to-1.1.0.sh

* Update automated release workflow to add input of enterprise image tag
* Updated documentation

Changes for 1.1.0 release

---

.github/workflows/automated-release-workflow.yml
.github/workflows/pre-release-workflow.yml

* Updated the release directory name in automated release workflow
* Removed redundant step from pre release workflow

Update release workflow logic

---

docs/SplunkOperatorUpgrade.md
test/run-tests.sh
tools/upgrade-to-1.1.0.sh

1. added upgrade script download step

updated document changes for upgrade scenario

---

bundle/manifests/splunk-operator.clusterserviceversion.yaml
docs/ChangeLog.md
docs/SplunkOperatorUpgrade.md
tools/upgrade-to-1.1.0.sh

1. fixed formatting issues
2. fixed docker image version for splunk

Fixed formatting and version of Splunk docker image

---

README.md
test/README.md
test/run-tests.sh
tools/upgrade-to-1.1.0.sh

Minor doc changes after 1.1.0 release.

Minor doc changes after 1.1.0 release

---

test/deploy-eks-cluster.sh
test/run-tests.sh

Co-authored-by: Sirish Mohan <68884189+smohan-splunk@users.noreply.github.com>
(cherry picked from commit bba64a86b1aa42ac1e40bd7a7294ccfe8d7681f6)
Backport of PR https://github.com/splunk/splunk-operator/pull/741

Removed PVC cleanup to make cluster-down (#741)

---

test/c3/appframework/appframework_test.go
test/m4/appframework/appframework_test.go
test/s1/appframework/appframework_test.go
test/testenv/deployment.go
test/testenv/util.go
test/testenv/verificationutils.go

Fix Issues with pipeline
Int test run: https://github.com/splunk/splunk-operator/runs/6011142014?check_suite_focus=true

rebase changes with PR:707

---

.github/workflows/int-test-workflow.yml

Enabled Int test on feature appframework.

Enabled int test on feature appframework

---

.github/workflows/automated-release-workflow.yml

Correct splunk enterprise image name in the release workflow

CSPL-1725: fixed splunk image tag

---

pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/util.go

Addressing the format and missing key/values for the logging

CSPL-1757: Correct the log key value pairs

---

pkg/splunk/util/secrets.go

fixing a log format that is causing the panic

CSPL-1765: fixing a log format that is causing the panic

---

docs/Examples.md

Fixing github issue - https://github.com/splunk/splunk-operator/issues/772

CSPL-1766 - MC documentation bug

---

Dockerfile

ubi security patch to docker images

CSPL-1777: Installing UBI security patch docker

---

.github/namespace-scope-int-workflow.yml

Adding a workflow to run integration tests with a namespace-scoped operator.
File is based on existing int-test-workflow.yml, with setting  CLUSTER_WIDE: "false" and is set to run twice a week, on wednesday and sunday at 02:00

CSPL 1754: Namespace scoped test automation

---

pkg/splunk/client/enterprise.go
pkg/splunk/common/util.go
pkg/splunk/enterprise/util.go

Cspl-1740-PR : addressed PR review comments for feature-appframework

---

config/default/kustomization-cluster.yaml
config/default/kustomization-namespace.yaml

Fixed an issue in generating manifests files for cluster/namespace scope. Signed-off-by: vivekr-splunk <94569031+vivekr-splunk@users.noreply.github.com>

CSPL-1833: fixed an issue in support PVC in appframework

---

test/testenv/verificationutils.go

Improved logging messages to make debug easier in case failed test cases for Pod Reset Check

Improved logging for pod reset util

---

.github/workflows/int-test-workflow.yml
.github/workflows/pre-release-workflow.yml
docs/ChangeLog.md
docs/SplunkOperatorUpgrade.md
pkg/splunk/controller/serviceaccount.go
pkg/splunk/controller/serviceaccount_test.go
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/test/minioclient.go
tools/operator-upgrade.sh

Addressed review comments here -> https://github.com/splunk/splunk-operator/pull/834

Address review comments on develop to master PR

---

.github/workflows/automated-release-workflow.yml
.github/workflows/namespace-scope-int-workflow.yml
.github/workflows/pre-release-workflow.yml

- Corrected the image name in release workflow
- Corrected release artifact names in release workflow
- Added bundle creation to pre release
- Updated golint install method in namespace scope operator workflow

Cspl 1963 - Fix workflow issues on master branch

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
.github/workflows/manual-int-test-workflow.yml
.github/workflows/merge-develop-to-master-workflow.yml
.github/workflows/namespace-scope-int-workflow.yml
.github/workflows/nightly-int-test-workflow.yml
.github/workflows/pre-release-workflow.yml
Makefile

- Added make cmd for ginkgo and golint
- Modified install methods in the workflows

CSPL-1974-add-make-cmd-for-ginkgo-golint-install

---

pkg/splunk/enterprise/configuration_test.go

Added unit test for getProbeWithConfigUpdates

Cspl 2003- Added unit test for getProbeWithConfigUpdates

---

Dockerfile

https://splunk.atlassian.net/browse/CSPL-2016 based on customer issue we are planning to support updating container with low, moderate and critical security updates. 
changes are only in docker file

cspl-2016: security patch updates for splunk operator container

---

config/crd/patches/additional_supported_versions_patch_clustermasters.yaml
config/crd/patches/additional_supported_versions_patch_indexerclusters.yaml
config/crd/patches/additional_supported_versions_patch_licensemasters.yaml
config/crd/patches/additional_supported_versions_patch_searchheadclusters.yaml
config/crd/patches/additional_supported_versions_patch_standalones.yaml

removed support for 
v1alpha1
v1beta1
v1beta2
v1beta3

cspl-2017:  removed support for Alpha and Beta splunk operator CRD

---

kuttl/kuttl-test-helm.yaml
kuttl/tests/helm/c3/01-assert.yaml
kuttl/tests/helm/c3/01-install-c3.yaml
kuttl/tests/helm/c3/02-assert.yaml
kuttl/tests/helm/c3/02-scaleup-c3.yaml
kuttl/tests/helm/m4/01-assert.yaml
kuttl/tests/helm/m4/01-install-m4.yaml
kuttl/tests/helm/m4/new_values.yaml
kuttl/tests/helm/s1/00-install-service-account.yaml
kuttl/tests/helm/s1/01-assert.yaml
kuttl/tests/helm/s1/01-install-standalone.yaml
kuttl/tests/helm/s1/02-assert.yaml
kuttl/tests/helm/s1/02-scaleup-standalone.yaml
kuttl/tests/helm/s1/03-assert.yaml
kuttl/tests/helm/s1/03-rollback-standalone.yaml
kuttl/tests/helm/s1/04-assert.yaml
kuttl/tests/helm/s1/04-monitoringconsole-standalone.yaml
kuttl/tests/helm/s1/05-assert.yaml
kuttl/tests/helm/s1/05-licensemaster-standalone.yaml
kuttl/tests/helm/s1/06-delete-standalone.yaml
kuttl/tests/helm/s1/06-errors.yaml

Automation local run result
```
=== CONT  kuttl
harness.go:402: run tests finished
harness.go:511: cleaning up
harness.go:568: removing temp folder: ""
--- PASS: kuttl (1505.94s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/c3 (418.04s)
--- PASS: kuttl/harness/s1 (452.80s)
--- PASS: kuttl/harness/m4 (606.40s)
PASS
tpereira@C02D15YMMD6R splunk-operator %
```

CSPL-1987: Automation for helmcharts

---

pkg/splunk/enterprise/names.go
pkg/splunk/enterprise/util.go

Added 2 APIs to set K8_OPERATOR_LIVENESS_LEVEL for CR and Pods.

CSPL-1980: Add API to add support for K8_OPERATOR_LIVENESS_LEVEL

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
bundle/metadata/annotations.yaml
controllers/clustermaster_controller_test.go

* Removed deployment type helm from int test and build-test workflows 
* Restored operator sdk version in annotations.yaml
* Fixed a typo

Fix issues on develop identified during develop merge to feature-readiness-liveness-configurable

---

test/run-tests.sh

merge develop to appframework_azureblob to pickup the false positive test fix.

CSPL-2081: Develop to azureblob merge to take false positive fix 

---

config/examples/advanced/c1_azure_blob.yaml
config/examples/advanced/c3.yaml
config/examples/advanced/c3_azure_blob.yaml
config/examples/advanced/hwf_azure_blob.yaml
config/examples/advanced/s1_azure_blob.yaml
config/examples/clustermanager/default.yaml
config/examples/indexercluster/default.yaml
config/examples/licensemanager/default.yaml
config/examples/monitoringconsole/default.yaml
config/examples/searchheadcluster/default.yaml
config/examples/standalone/default.yaml
docs/AppFramework.md

PR for covering updates for the following tasks:
https://splunk.atlassian.net/browse/CSPL-2063
**Update the app framework doc to include:**
- Examples of azure blob usage 
- Steps for using managed identity for azure blob
https://splunk.atlassian.net/browse/CSPL-2064
**Addition of new examples**
Added new examples similar to S3 to show usage of azure blob 
Removed smart store sections from azure blob examples
**Updated v3 to v4**

CSPL-2063: Update app framework doc to include azure blob usages

---

.github/workflows/int-test-workflow.yml
test/appframework/aws/c3/appframework_aws_suite_test.go
test/appframework/aws/m4/appframework_aws_suite_test.go
test/appframework/aws/s1/appframework_aws_suite_test.go
test/appframework/azure/c3/appframework_azure_suite_test.go
test/appframework/azure/c3/appframework_azure_test.go
test/appframework/azure/c3/manager_appframework_azure_test.go
test/appframework/azure/m4/appframework_azure_suite_test.go
test/appframework/azure/m4/appframework_azure_test.go
test/appframework/azure/m4/manager_appframework_azure_test.go
test/appframework/azure/s1/appframework_azure_suite_test.go
test/appframework/azure/s1/appframework_azure_test.go
test/testenv/s3utils.go

- Update test to check platform before running test setup
- Add feature branch to int test

Update Test to check cluster platform before running test

---

.github/workflows/int-test-workflow.yml

Fixed the int test on AzureBlob

CSPL-2101: Fix int test on azureblob

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/helm-test-workflow.yml
.github/workflows/int-test-workflow.yml
.github/workflows/manual-int-test-workflow.yml
.github/workflows/namespace-scope-int-workflow.yml
.github/workflows/nightly-int-test-workflow.yml
test/deploy-eks-cluster.sh
test/env.sh

Make the EKS Cluster version configurable.

Configure k8 version of EKS Cluster

---

.env
test/appframework_az/c3/appframework_azure_test.go
test/testenv/deployment.go

fixed the errors in MasterSuite in azure framework spec

fix master suite test cases to use masterSpec

---

.env

Removed users which are not found on github

Fix reviewer list

---

docs/HealthCheck.md
pkg/splunk/controller/util.go
pkg/splunk/controller/util_test.go

* Added logic to update the pods with latest changes for probe values
* Updates probes example in docs

CSPL-2126: Fixed probe updates

---

docs/SplunkOperatorUpgrade.md
tools/operator-upgrade.sh

Update the upgrade commands according to the info here: https://github.com/kubernetes/kubernetes/issues/80916

Update upgrade procedure docs

---

.github/workflows/merge-develop-to-master-workflow.yml

Removed redundant `"` from bash commands.

Fixed workflow issues

---

tools/bias_lang_migration.sh

adding node affinity of cluster manager to upgrade job

cspl-2149: added node affinity to job

---

test/appframework_aws/c3/appframework_aws_test.go
test/appframework_aws/c3/manager_appframework_test.go
test/appframework_aws/s1/appframework_aws_test.go
test/appframework_az/c3/appframework_azure_test.go
test/appframework_az/c3/manager_appframework_azure_test.go
test/appframework_az/s1/appframework_azure_test.go

Edited ES test cases. 
- Added new scope 
- Updated with latest verification functions

CSPL-2112 Initial changes for ES app

---

tools/bias_lang_migration.sh

while upgrading added validation to set maintenance mode

Cspl-2149 : added validation to set maintenance mode 

---

.github/workflows/bundle-push-post-release.yml
.github/workflows/pre-release-workflow.yml
docs/ChangeLog.md

Added missing make generate command

Update workflow to run additional make generate steps

---

.github/workflows/helm-test-workflow.yml
docs/ChangeLog.md
kuttl/tests/helm/m4/m4_config.yaml

test cases were failing due to zone not available. i have changed the zone to use 2b and 2c.

change helm m4 test to use zone 2b and 2c

---

api/v4/common_types.go
config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
config/crd/bases/enterprise.splunk.com_clustermasters.yaml
config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
config/crd/bases/enterprise.splunk.com_licensemasters.yaml
config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
config/crd/bases/enterprise.splunk.com_standalones.yaml
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/afwscheduler_test.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/configuration_test.go
pkg/splunk/enterprise/types.go
pkg/splunk/util/messages.go
pkg/splunk/util/util.go
pkg/splunk/util/util_test.go

Initial draft changes for enabling ES app on operator using appFramework

Changes for enabling ES app on operator using appFramework for standalone and SHC

---

.github/workflows/build-test-push-workflow.yml
Makefile

Add Static analysis against code. Commands to run:
Run `make scheck`

CSPL-2156 - Add Static analysis against code

---

.github/workflows/prodsec-workflow.yml
api/v4/common_types.go
config/crd/bases/enterprise.splunk.com_clustermanagers.yaml
config/crd/bases/enterprise.splunk.com_clustermasters.yaml
config/crd/bases/enterprise.splunk.com_licensemanagers.yaml
config/crd/bases/enterprise.splunk.com_licensemasters.yaml
config/crd/bases/enterprise.splunk.com_monitoringconsoles.yaml
config/crd/bases/enterprise.splunk.com_searchheadclusters.yaml
config/crd/bases/enterprise.splunk.com_standalones.yaml
pkg/splunk/enterprise/afwscheduler.go
pkg/splunk/enterprise/configuration.go
pkg/splunk/enterprise/configuration_test.go

Make ssl_enablement ignore as default, disable strict for shc

CSPL-2187 - Make ssl_enablement ignore as default, disable strict for shc

---

.github/workflows/prodsec-workflow.yml
docs/PremiumApps.md

Add docs for ES installation within premium apps doc.
Includes:
Steps for installing ES from operator
Compatibility matrices (ES/ Splunk enterprise)
Examples for Standalone, SHC with indexer cluster
Special handling for strict mode of ssl enablement

CSPL-1583: Update docs for ES app installation

---

pkg/splunk/enterprise/afwscheduler.go

**Problem:** 
The app packages on the operator were not getting deleted. The API `cleanupApp` which deletes the app package on the target splunk pod and the operator pod checks for phaseInfo in an internal call to `deleteAppPkgFromOperator`. We are setting the phaseInfo in `markWorkerPhaseInstallationComplete` after the call to `cleanupApp`.
**Solution:**
Call `markWorkerPhaseInstallationComplete` before `cleanupApp` so the delete goes through fine.
Added logs to record successful deletion of app packages on target pod as well as operator pod.
Logs from local test where apps were deleted successfully:
```
2023-01-09T20:55:07.734275563Z  INFO    cleanupApp      App package deleted from target pod       {"controller": "standalone", "controllerGroup": "enterprise.splunk.com", …
```

Marking phase info before deleting app package on operator 

---

.github/workflows/nightly-int-test-workflow.yml

Fixed Nightly test to pull correct branch for image creation.

Updated checkout action to pull develop branch for image creation

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml

CSPL-2277: Update the branch name check for main branch in workflows
CSPL-2273: Update the workflows with regex to match the feature branch
CSPL-2276: [QA] Disable master test cases from smoke tests

Fix the workflow issues identified during release

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
bundle/manifests/splunk-operator.clusterserviceversion.yaml
config/manifests/bases/splunk-operator.clusterserviceversion.yaml
docs/README.md

PR to sync develop with main branch

Main to develop PR 

---

helm-chart/splunk-enterprise/templates/enterprise_v4_standalone.yaml

https://github.com/splunk/splunk-operator/issues/1063

solves issue #1063

---

kuttl/tests/helm/s1-with-extra-manifests/00-install-service-account.yaml
kuttl/tests/helm/s1-with-extra-manifests/01-assert.yaml
kuttl/tests/helm/s1-with-extra-manifests/01-install-standalone.yaml
kuttl/tests/helm/s1-with-extra-manifests/s1_config.yaml

helm test to test extra manifests

CSPL-2282: helm: test case to test extraManifests

---

Makefile

fixed build issue for develop branch

Build issues

---

.github/workflows/pre-release-workflow.yml

fixed some issues in prerelease workflow

Pre release workflow fix

---

.github/workflows/helm-test-workflow.yml
kuttl/tests/helm/script/installoperator.sh

some of the test are using public image i am changing that to use image created in pipeline

fixed image version in helm test

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/helm-test-workflow.yml

workflow changes to get splunk release image tag.

fixed release workflow splunk image tag

---

.github/workflows/build-test-push-workflow.yml
.github/workflows/int-test-workflow.yml
docs/Helm.md
docs/PasswordManagement.md

Documentation for OIDC support with the Splunk Operator

cspl-2331: documentation changes for OIDC support

---

.github/workflows/build-test-push-workflow.yml
docs/Helm.md

fixed run step for environment setup

Workflow changes 1

---

test/deploy-eks-cluster.sh

Fixed role deletion in cluster deletion step
- Delete policy attachments
- Delete Role

pipeline fix for 1.26 k8s deletion

---

.github/workflows/int-test-workflow.yml
docs/ChangeLog.md
docs/Images.md
docs/README.md

1. removed all the splunk version related things from docs
2. Add support matrix to release page

Document Changes to support 2.4.0 release

---

README.md
bundle.Dockerfile
bundle/manifests/splunk-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
docs/ChangeLog.md
helm-chart/splunk-enterprise/Chart.yaml
helm-chart/splunk-operator/Chart.yaml
helm-chart/splunk-operator/values.yaml

helm version upgraded to 2.4.0
Operator bundle generated for 2.4.0

Helm 2.4.0 and Operator Bundle changes

---

.github/workflows/int-test-azure-workflow.yml

Few changes were done to Azure pipeline, current credentials were not working for docker image pull/push
changed the workflow and github secrets

changes to support azure docker login 

---

.github/workflows/helm-test-workflow.yml
kuttl/tests/helm/c3-with-apps/03-install-c3.yaml
kuttl/tests/helm/c3-with-operator/00-install-c3.yaml

helm test case fix

---

docs/ChangeLog.md

change log date fixed for 2-05

change log date fixed

---

pkg/splunk/enterprise/util.go

security context for init container is not set

cspl-2535: security context for init container not set

---

.github/workflows/pre-release-workflow.yml

Update pre-release-workflow for helm charts

Pre release workflow update

---

.github/workflows/pre-release-workflow.yml

Update gha-find-replace version, helm chart update

Update gha-find-replace version, helm chart update

---

Dockerfile
bundle/manifests/enterprise.splunk.com_clustermanagers.yaml
bundle/manifests/enterprise.splunk.com_clustermasters.yaml
bundle/manifests/enterprise.splunk.com_indexerclusters.yaml
bundle/manifests/enterprise.splunk.com_licensemanagers.yaml
bundle/manifests/enterprise.splunk.com_licensemasters.yaml
bundle/manifests/enterprise.splunk.com_monitoringconsoles.yaml
bundle/manifests/enterprise.splunk.com_searchheadclusters.yaml
bundle/manifests/enterprise.splunk.com_standalones.yaml
bundle/manifests/splunk-operator.clusterserviceversion.yaml
config/manifests/bases/splunk-operator.clusterserviceversion.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_clustermanagers.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_clustermasters.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_indexerclusters.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_licensemanagers.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_licensemasters.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_monitoringconsoles.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_searchheadclusters.yaml
helm-chart/splunk-operator/crds/enterprise.splunk.com_standalones.yaml

Merge extra changes from [MR](https://github.com/splunk/splunk-operator/pull/1380) to develop

Merge extra changes from promote-develop-to-main-2.6.1 to develop

---

docs/Examples.md

Merge main back to develop for: Fixes PR#1377

Merge main back to develop for: Fixes PR#1377

---

test/env.sh

CSPL-2887 - Change eks version to 1.31

CSPL-2887 - Change eks version to 1.31

---

.github/pull_request_template.md

Creation of a pull_request_template.md file to automatically populate PR descriptions with headlines.
- pull_request_template.md
- File created with headlines and prompts for users.
N/A
[CSPL-3527](https://splunk.atlassian.net/browse/CSPL-3527) - Create Pull Request Template for Github Repo

CSPL-3527: Add pull request template

---

.env
.github/ISSUE_TEMPLATE/app-framework.yml
.github/ISSUE_TEMPLATE/generic.yml
.github/ISSUE_TEMPLATE/ingress.yml
.github/ISSUE_TEMPLATE/monitoring-console.yml
.github/ISSUE_TEMPLATE/secret-management.yml
.github/ISSUE_TEMPLATE/smartstore.yml
README.md
docs/CONTRIBUTING.md
docs/artifacthub-repo.yml
helm-chart/splunk-enterprise/Chart.yaml
helm-chart/splunk-operator/Chart.yaml

This pull request updates the maintainers of the project.
Issue Templates:
- Remove assignees. The team goes through on a regular basis to assign issues.
README.md
- Remove CircleCI as it is no longer used.
docs/helm charts
- Update active members
N/A
- https://splunk.atlassian.net/browse/CSPL-3674

CSPL-3674: Update project maintainers

---

Makefile
helm-chart/splunk-enterprise/Chart.yaml
helm-chart/splunk-operator/Chart.yaml

This PR updates Chart.yaml files to support 2.8.0 release.
Changing 2.7.1 version to 2.8.0.
No manual tests required. Automated tests executed automatically as a part of the process.
[https://splunk.atlassian.net/browse/CSPL-3534](https://splunk.atlassian.net/browse/CSPL-3624)

CSPL-3624 Update Chart.yaml files to support 2.8.0 release

---

.github/workflows/pre-release-workflow.yml

This pull request enhances the pre-release workflow by adding steps to automate version updates and configuration adjustments for the Splunk Operator. The changes aim to streamline the preparation process for new releases by ensuring files are updated consistently and accurately.
* **Update Splunk Operator version in `Dockerfile`:** Added a step to replace the old operator version with the new one in the `Dockerfile` if the versions differ. (`.github/workflows/pre-release-workflow.yml`, [.github/workflows/pre-release-workflow.ymlR144-R151](diffhunk://#diff-e32d147e7ce8f417d6108de5f4ba76eb8494cf17b1f1e1d3c6460a1b868c544aR144-R151))
* **Update Splunk Operator release version in bundle files:** Added a step to update the operator version in all YAML files within the bundle, excluding …

CSPL-3688: Update Prerelease Workflow

---

Makefile

This PR replaces () in all variable references in the script to use {}.
Replacing () to {}.
No new automation required. Tests performed as a part of the pipeline run (https://github.com/splunk/splunk-operator/pull/1519).
Jira: https://splunk.atlassian.net/browse/CSPL-3702

CSPL-3702 Fix script variables to use {} instead of ()

---

docs/SmartStore.md

This PR updates the SmartStore documentation with information on using it via Azure or GCP.
- Add SmartStore as supported on Azure through Splunk App.
- Add information about credential storage.
N/A
- https://splunk.atlassian.net/browse/CSPL-3869

[CSPL-3869] Update SmartStore documentation for GCP and Azure

---

.github/workflows/distroless-build-test-push-workflow.yml
.github/workflows/merge-develop-to-main-workflow.yml
Makefile
README.md
bundle.Dockerfile
docs/AppFramework.md
docs/Examples.md
docs/Ingress.md

This PR fixes the distroless workflows, and some typos in the documentation files.
- [distroless-build-test-push-workflow.yml](https://github.com/splunk/splunk-operator/compare/develop...pipeline_doc_fixes?expand=1#diff-0d86a44c8d0e0778e49cc4909a6a1a99176ba84a269d9b89b11e264abd4ea9ac): set base image and version
- [merge-develop-to-main-workflow.yml](https://github.com/splunk/splunk-operator/compare/develop...pipeline_doc_fixes?expand=1#diff-1ba768cddb3d672813a588f9d2d8ccdf3b55a2479b1bf1af6a131c30cb7d65a8): set `-distroless` in image name since it will not be done by the Makefile
- [Makefile](https://github.com/splunk/splunk-operator/compare/develop...pipeline_doc_fixes?expand=1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52): remove automatically adding …

Pipeline and documentation fixes
